blank_issues_enabled: false
contact_links:
  - name: Discussions and support
    url: https://github.com/mikkokko/csgo_gc/discussions
    about: For support, general discussion, sharing ideas, or self-promotion. Do not open an issue for these.
