// Automatically generated by scripts/steamproxygen.py, do not modify!!!
#ifndef STEAMUSERSTATSPROXY009_H
#define STEAMUSERSTATSPROXY009_H

#include "steamproxy.h"
#include <steam_old/isteamuserstats009.h>

class SteamUserStatsProxy009 final : public ISteamUserStats009
{
    ISteamUserStats009 *m_original;
    SteamUserStatsProxy *m_proxy;

public:
    SteamUserStatsProxy009(ISteamUserStats009 *original, SteamUserStatsProxy *proxy)
        : m_original{ original }
        , m_proxy{ proxy }
    {
    }

    bool RequestCurrentStats() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUserStats009::RequestCurrentStats>(m_original);
            if constexpr (requires { p->RequestCurrentStats(o); })
                return p->RequestCurrentStats(o);
            else
                return o();
        }(m_proxy);
    }

    bool GetStat(const char *pchName, int32 *pData) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<static_cast<bool (ISteamUserStats009::*)(const char *, int32 *)>(&ISteamUserStats009::GetStat)>(m_original);
            if constexpr (requires { p->GetStat(o, pchName, pData); })
                return p->GetStat(o, pchName, pData);
            else
                return o(pchName, pData);
        }(m_proxy);
    }

    bool GetStat(const char *pchName, float *pData) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<static_cast<bool (ISteamUserStats009::*)(const char *, float *)>(&ISteamUserStats009::GetStat)>(m_original);
            if constexpr (requires { p->GetStat(o, pchName, pData); })
                return p->GetStat(o, pchName, pData);
            else
                return o(pchName, pData);
        }(m_proxy);
    }

    bool SetStat(const char *pchName, int32 nData) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<static_cast<bool (ISteamUserStats009::*)(const char *, int32)>(&ISteamUserStats009::SetStat)>(m_original);
            if constexpr (requires { p->SetStat(o, pchName, nData); })
                return p->SetStat(o, pchName, nData);
            else
                return o(pchName, nData);
        }(m_proxy);
    }

    bool SetStat(const char *pchName, float fData) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<static_cast<bool (ISteamUserStats009::*)(const char *, float)>(&ISteamUserStats009::SetStat)>(m_original);
            if constexpr (requires { p->SetStat(o, pchName, fData); })
                return p->SetStat(o, pchName, fData);
            else
                return o(pchName, fData);
        }(m_proxy);
    }

    bool UpdateAvgRateStat(const char *pchName, float flCountThisSession, double dSessionLength) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUserStats009::UpdateAvgRateStat>(m_original);
            if constexpr (requires { p->UpdateAvgRateStat(o, pchName, flCountThisSession, dSessionLength); })
                return p->UpdateAvgRateStat(o, pchName, flCountThisSession, dSessionLength);
            else
                return o(pchName, flCountThisSession, dSessionLength);
        }(m_proxy);
    }

    bool GetAchievement(const char *pchName, bool *pbAchieved) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUserStats009::GetAchievement>(m_original);
            if constexpr (requires { p->GetAchievement(o, pchName, pbAchieved); })
                return p->GetAchievement(o, pchName, pbAchieved);
            else
                return o(pchName, pbAchieved);
        }(m_proxy);
    }

    bool SetAchievement(const char *pchName) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUserStats009::SetAchievement>(m_original);
            if constexpr (requires { p->SetAchievement(o, pchName); })
                return p->SetAchievement(o, pchName);
            else
                return o(pchName);
        }(m_proxy);
    }

    bool ClearAchievement(const char *pchName) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUserStats009::ClearAchievement>(m_original);
            if constexpr (requires { p->ClearAchievement(o, pchName); })
                return p->ClearAchievement(o, pchName);
            else
                return o(pchName);
        }(m_proxy);
    }

    bool GetAchievementAndUnlockTime(const char *pchName, bool *pbAchieved, uint32 *punUnlockTime) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUserStats009::GetAchievementAndUnlockTime>(m_original);
            if constexpr (requires { p->GetAchievementAndUnlockTime(o, pchName, pbAchieved, punUnlockTime); })
                return p->GetAchievementAndUnlockTime(o, pchName, pbAchieved, punUnlockTime);
            else
                return o(pchName, pbAchieved, punUnlockTime);
        }(m_proxy);
    }

    bool StoreStats() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUserStats009::StoreStats>(m_original);
            if constexpr (requires { p->StoreStats(o); })
                return p->StoreStats(o);
            else
                return o();
        }(m_proxy);
    }

    int GetAchievementIcon(const char *pchName) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamUserStats009::GetAchievementIcon>(m_original);
            if constexpr (requires { p->GetAchievementIcon(o, pchName); })
                return p->GetAchievementIcon(o, pchName);
            else
                return o(pchName);
        }(m_proxy);
    }

    const char *GetAchievementDisplayAttribute(const char *pchName, const char *pchKey) override
    {
        return [&](auto p) -> const char *
        {
            auto o = MakeOrig<&ISteamUserStats009::GetAchievementDisplayAttribute>(m_original);
            if constexpr (requires { p->GetAchievementDisplayAttribute(o, pchName, pchKey); })
                return p->GetAchievementDisplayAttribute(o, pchName, pchKey);
            else
                return o(pchName, pchKey);
        }(m_proxy);
    }

    bool IndicateAchievementProgress(const char *pchName, uint32 nCurProgress, uint32 nMaxProgress) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUserStats009::IndicateAchievementProgress>(m_original);
            if constexpr (requires { p->IndicateAchievementProgress(o, pchName, nCurProgress, nMaxProgress); })
                return p->IndicateAchievementProgress(o, pchName, nCurProgress, nMaxProgress);
            else
                return o(pchName, nCurProgress, nMaxProgress);
        }(m_proxy);
    }

    SteamAPICall_t RequestUserStats(CSteamID steamIDUser) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamUserStats009::RequestUserStats>(m_original);
            if constexpr (requires { p->RequestUserStats(o, steamIDUser); })
                return p->RequestUserStats(o, steamIDUser);
            else
                return o(steamIDUser);
        }(m_proxy);
    }

    bool GetUserStat(CSteamID steamIDUser, const char *pchName, int32 *pData) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<static_cast<bool (ISteamUserStats009::*)(CSteamID, const char *, int32 *)>(&ISteamUserStats009::GetUserStat)>(m_original);
            if constexpr (requires { p->GetUserStat(o, steamIDUser, pchName, pData); })
                return p->GetUserStat(o, steamIDUser, pchName, pData);
            else
                return o(steamIDUser, pchName, pData);
        }(m_proxy);
    }

    bool GetUserStat(CSteamID steamIDUser, const char *pchName, float *pData) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<static_cast<bool (ISteamUserStats009::*)(CSteamID, const char *, float *)>(&ISteamUserStats009::GetUserStat)>(m_original);
            if constexpr (requires { p->GetUserStat(o, steamIDUser, pchName, pData); })
                return p->GetUserStat(o, steamIDUser, pchName, pData);
            else
                return o(steamIDUser, pchName, pData);
        }(m_proxy);
    }

    bool GetUserAchievement(CSteamID steamIDUser, const char *pchName, bool *pbAchieved) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUserStats009::GetUserAchievement>(m_original);
            if constexpr (requires { p->GetUserAchievement(o, steamIDUser, pchName, pbAchieved); })
                return p->GetUserAchievement(o, steamIDUser, pchName, pbAchieved);
            else
                return o(steamIDUser, pchName, pbAchieved);
        }(m_proxy);
    }

    bool GetUserAchievementAndUnlockTime(CSteamID steamIDUser, const char *pchName, bool *pbAchieved, uint32 *punUnlockTime) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUserStats009::GetUserAchievementAndUnlockTime>(m_original);
            if constexpr (requires { p->GetUserAchievementAndUnlockTime(o, steamIDUser, pchName, pbAchieved, punUnlockTime); })
                return p->GetUserAchievementAndUnlockTime(o, steamIDUser, pchName, pbAchieved, punUnlockTime);
            else
                return o(steamIDUser, pchName, pbAchieved, punUnlockTime);
        }(m_proxy);
    }

    bool ResetAllStats(bool bAchievementsToo) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUserStats009::ResetAllStats>(m_original);
            if constexpr (requires { p->ResetAllStats(o, bAchievementsToo); })
                return p->ResetAllStats(o, bAchievementsToo);
            else
                return o(bAchievementsToo);
        }(m_proxy);
    }

    SteamAPICall_t FindOrCreateLeaderboard(const char *pchLeaderboardName, ELeaderboardSortMethod eLeaderboardSortMethod, ELeaderboardDisplayType eLeaderboardDisplayType) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamUserStats009::FindOrCreateLeaderboard>(m_original);
            if constexpr (requires { p->FindOrCreateLeaderboard(o, pchLeaderboardName, eLeaderboardSortMethod, eLeaderboardDisplayType); })
                return p->FindOrCreateLeaderboard(o, pchLeaderboardName, eLeaderboardSortMethod, eLeaderboardDisplayType);
            else
                return o(pchLeaderboardName, eLeaderboardSortMethod, eLeaderboardDisplayType);
        }(m_proxy);
    }

    SteamAPICall_t FindLeaderboard(const char *pchLeaderboardName) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamUserStats009::FindLeaderboard>(m_original);
            if constexpr (requires { p->FindLeaderboard(o, pchLeaderboardName); })
                return p->FindLeaderboard(o, pchLeaderboardName);
            else
                return o(pchLeaderboardName);
        }(m_proxy);
    }

    const char *GetLeaderboardName(SteamLeaderboard_t hSteamLeaderboard) override
    {
        return [&](auto p) -> const char *
        {
            auto o = MakeOrig<&ISteamUserStats009::GetLeaderboardName>(m_original);
            if constexpr (requires { p->GetLeaderboardName(o, hSteamLeaderboard); })
                return p->GetLeaderboardName(o, hSteamLeaderboard);
            else
                return o(hSteamLeaderboard);
        }(m_proxy);
    }

    int GetLeaderboardEntryCount(SteamLeaderboard_t hSteamLeaderboard) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamUserStats009::GetLeaderboardEntryCount>(m_original);
            if constexpr (requires { p->GetLeaderboardEntryCount(o, hSteamLeaderboard); })
                return p->GetLeaderboardEntryCount(o, hSteamLeaderboard);
            else
                return o(hSteamLeaderboard);
        }(m_proxy);
    }

    ELeaderboardSortMethod GetLeaderboardSortMethod(SteamLeaderboard_t hSteamLeaderboard) override
    {
        return [&](auto p) -> ELeaderboardSortMethod
        {
            auto o = MakeOrig<&ISteamUserStats009::GetLeaderboardSortMethod>(m_original);
            if constexpr (requires { p->GetLeaderboardSortMethod(o, hSteamLeaderboard); })
                return p->GetLeaderboardSortMethod(o, hSteamLeaderboard);
            else
                return o(hSteamLeaderboard);
        }(m_proxy);
    }

    ELeaderboardDisplayType GetLeaderboardDisplayType(SteamLeaderboard_t hSteamLeaderboard) override
    {
        return [&](auto p) -> ELeaderboardDisplayType
        {
            auto o = MakeOrig<&ISteamUserStats009::GetLeaderboardDisplayType>(m_original);
            if constexpr (requires { p->GetLeaderboardDisplayType(o, hSteamLeaderboard); })
                return p->GetLeaderboardDisplayType(o, hSteamLeaderboard);
            else
                return o(hSteamLeaderboard);
        }(m_proxy);
    }

    SteamAPICall_t DownloadLeaderboardEntries(SteamLeaderboard_t hSteamLeaderboard, ELeaderboardDataRequest eLeaderboardDataRequest, int nRangeStart, int nRangeEnd) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamUserStats009::DownloadLeaderboardEntries>(m_original);
            if constexpr (requires { p->DownloadLeaderboardEntries(o, hSteamLeaderboard, eLeaderboardDataRequest, nRangeStart, nRangeEnd); })
                return p->DownloadLeaderboardEntries(o, hSteamLeaderboard, eLeaderboardDataRequest, nRangeStart, nRangeEnd);
            else
                return o(hSteamLeaderboard, eLeaderboardDataRequest, nRangeStart, nRangeEnd);
        }(m_proxy);
    }

    SteamAPICall_t DownloadLeaderboardEntriesForUsers(SteamLeaderboard_t hSteamLeaderboard, CSteamID *prgUsers, int cUsers) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamUserStats009::DownloadLeaderboardEntriesForUsers>(m_original);
            if constexpr (requires { p->DownloadLeaderboardEntriesForUsers(o, hSteamLeaderboard, prgUsers, cUsers); })
                return p->DownloadLeaderboardEntriesForUsers(o, hSteamLeaderboard, prgUsers, cUsers);
            else
                return o(hSteamLeaderboard, prgUsers, cUsers);
        }(m_proxy);
    }

    bool GetDownloadedLeaderboardEntry(SteamLeaderboardEntries_t hSteamLeaderboardEntries, int index, LeaderboardEntry_t *pLeaderboardEntry, int32 *pDetails, int cDetailsMax) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUserStats009::GetDownloadedLeaderboardEntry>(m_original);
            if constexpr (requires { p->GetDownloadedLeaderboardEntry(o, hSteamLeaderboardEntries, index, pLeaderboardEntry, pDetails, cDetailsMax); })
                return p->GetDownloadedLeaderboardEntry(o, hSteamLeaderboardEntries, index, pLeaderboardEntry, pDetails, cDetailsMax);
            else
                return o(hSteamLeaderboardEntries, index, pLeaderboardEntry, pDetails, cDetailsMax);
        }(m_proxy);
    }

    SteamAPICall_t UploadLeaderboardScore(SteamLeaderboard_t hSteamLeaderboard, ELeaderboardUploadScoreMethod eLeaderboardUploadScoreMethod, int32 nScore, const int32 *pScoreDetails, int cScoreDetailsCount) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamUserStats009::UploadLeaderboardScore>(m_original);
            if constexpr (requires { p->UploadLeaderboardScore(o, hSteamLeaderboard, eLeaderboardUploadScoreMethod, nScore, pScoreDetails, cScoreDetailsCount); })
                return p->UploadLeaderboardScore(o, hSteamLeaderboard, eLeaderboardUploadScoreMethod, nScore, pScoreDetails, cScoreDetailsCount);
            else
                return o(hSteamLeaderboard, eLeaderboardUploadScoreMethod, nScore, pScoreDetails, cScoreDetailsCount);
        }(m_proxy);
    }

    SteamAPICall_t AttachLeaderboardUGC(SteamLeaderboard_t hSteamLeaderboard, UGCHandle_t hUGC) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamUserStats009::AttachLeaderboardUGC>(m_original);
            if constexpr (requires { p->AttachLeaderboardUGC(o, hSteamLeaderboard, hUGC); })
                return p->AttachLeaderboardUGC(o, hSteamLeaderboard, hUGC);
            else
                return o(hSteamLeaderboard, hUGC);
        }(m_proxy);
    }

    SteamAPICall_t GetNumberOfCurrentPlayers() override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamUserStats009::GetNumberOfCurrentPlayers>(m_original);
            if constexpr (requires { p->GetNumberOfCurrentPlayers(o); })
                return p->GetNumberOfCurrentPlayers(o);
            else
                return o();
        }(m_proxy);
    }
};

#endif // STEAMUSERSTATSPROXY009_H
