// Automatically generated by scripts/steamproxygen.py, do not modify!!!
#ifndef STEAMUTILSPROXY010_H
#define STEAMUTILSPROXY010_H

#include "steamproxy.h"
#include <steam_old/isteamutils010.h>

class SteamUtilsProxy010 final : public ISteamUtils010
{
    ISteamUtils010 *m_original;
    SteamUtilsProxy *m_proxy;

public:
    SteamUtilsProxy010(ISteamUtils010 *original, SteamUtilsProxy *proxy)
        : m_original{ original }
        , m_proxy{ proxy }
    {
    }

    uint32 GetSecondsSinceAppActive() override
    {
        return [&](auto p) -> uint32
        {
            auto o = MakeOrig<&ISteamUtils010::GetSecondsSinceAppActive>(m_original);
            if constexpr (requires { p->GetSecondsSinceAppActive(o); })
                return p->GetSecondsSinceAppActive(o);
            else
                return o();
        }(m_proxy);
    }

    uint32 GetSecondsSinceComputerActive() override
    {
        return [&](auto p) -> uint32
        {
            auto o = MakeOrig<&ISteamUtils010::GetSecondsSinceComputerActive>(m_original);
            if constexpr (requires { p->GetSecondsSinceComputerActive(o); })
                return p->GetSecondsSinceComputerActive(o);
            else
                return o();
        }(m_proxy);
    }

    EUniverse GetConnectedUniverse() override
    {
        return [&](auto p) -> EUniverse
        {
            auto o = MakeOrig<&ISteamUtils010::GetConnectedUniverse>(m_original);
            if constexpr (requires { p->GetConnectedUniverse(o); })
                return p->GetConnectedUniverse(o);
            else
                return o();
        }(m_proxy);
    }

    uint32 GetServerRealTime() override
    {
        return [&](auto p) -> uint32
        {
            auto o = MakeOrig<&ISteamUtils010::GetServerRealTime>(m_original);
            if constexpr (requires { p->GetServerRealTime(o); })
                return p->GetServerRealTime(o);
            else
                return o();
        }(m_proxy);
    }

    const char *GetIPCountry() override
    {
        return [&](auto p) -> const char *
        {
            auto o = MakeOrig<&ISteamUtils010::GetIPCountry>(m_original);
            if constexpr (requires { p->GetIPCountry(o); })
                return p->GetIPCountry(o);
            else
                return o();
        }(m_proxy);
    }

    bool GetImageSize(int iImage, uint32 *pnWidth, uint32 *pnHeight) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::GetImageSize>(m_original);
            if constexpr (requires { p->GetImageSize(o, iImage, pnWidth, pnHeight); })
                return p->GetImageSize(o, iImage, pnWidth, pnHeight);
            else
                return o(iImage, pnWidth, pnHeight);
        }(m_proxy);
    }

    bool GetImageRGBA(int iImage, uint8 *pubDest, int nDestBufferSize) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::GetImageRGBA>(m_original);
            if constexpr (requires { p->GetImageRGBA(o, iImage, pubDest, nDestBufferSize); })
                return p->GetImageRGBA(o, iImage, pubDest, nDestBufferSize);
            else
                return o(iImage, pubDest, nDestBufferSize);
        }(m_proxy);
    }

    bool GetCSERIPPort(uint32 *unIP, uint16 *usPort) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::GetCSERIPPort>(m_original);
            if constexpr (requires { p->GetCSERIPPort(o, unIP, usPort); })
                return p->GetCSERIPPort(o, unIP, usPort);
            else
                return o(unIP, usPort);
        }(m_proxy);
    }

    uint8 GetCurrentBatteryPower() override
    {
        return [&](auto p) -> uint8
        {
            auto o = MakeOrig<&ISteamUtils010::GetCurrentBatteryPower>(m_original);
            if constexpr (requires { p->GetCurrentBatteryPower(o); })
                return p->GetCurrentBatteryPower(o);
            else
                return o();
        }(m_proxy);
    }

    uint32 GetAppID() override
    {
        return [&](auto p) -> uint32
        {
            auto o = MakeOrig<&ISteamUtils010::GetAppID>(m_original);
            if constexpr (requires { p->GetAppID(o); })
                return p->GetAppID(o);
            else
                return o();
        }(m_proxy);
    }

    void SetOverlayNotificationPosition(ENotificationPosition eNotificationPosition) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUtils010::SetOverlayNotificationPosition>(m_original);
            if constexpr (requires { p->SetOverlayNotificationPosition(o, eNotificationPosition); })
                return p->SetOverlayNotificationPosition(o, eNotificationPosition);
            else
                return o(eNotificationPosition);
        }(m_proxy);
    }

    bool IsAPICallCompleted(SteamAPICall_t hSteamAPICall, bool *pbFailed) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::IsAPICallCompleted>(m_original);
            if constexpr (requires { p->IsAPICallCompleted(o, hSteamAPICall, pbFailed); })
                return p->IsAPICallCompleted(o, hSteamAPICall, pbFailed);
            else
                return o(hSteamAPICall, pbFailed);
        }(m_proxy);
    }

    ESteamAPICallFailure GetAPICallFailureReason(SteamAPICall_t hSteamAPICall) override
    {
        return [&](auto p) -> ESteamAPICallFailure
        {
            auto o = MakeOrig<&ISteamUtils010::GetAPICallFailureReason>(m_original);
            if constexpr (requires { p->GetAPICallFailureReason(o, hSteamAPICall); })
                return p->GetAPICallFailureReason(o, hSteamAPICall);
            else
                return o(hSteamAPICall);
        }(m_proxy);
    }

    bool GetAPICallResult(SteamAPICall_t hSteamAPICall, void *pCallback, int cubCallback, int iCallbackExpected, bool *pbFailed) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::GetAPICallResult>(m_original);
            if constexpr (requires { p->GetAPICallResult(o, hSteamAPICall, pCallback, cubCallback, iCallbackExpected, pbFailed); })
                return p->GetAPICallResult(o, hSteamAPICall, pCallback, cubCallback, iCallbackExpected, pbFailed);
            else
                return o(hSteamAPICall, pCallback, cubCallback, iCallbackExpected, pbFailed);
        }(m_proxy);
    }

    void RunFrame() override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUtils010::RunFrame>(m_original);
            if constexpr (requires { p->RunFrame(o); })
                return p->RunFrame(o);
            else
                return o();
        }(m_proxy);
    }

    uint32 GetIPCCallCount() override
    {
        return [&](auto p) -> uint32
        {
            auto o = MakeOrig<&ISteamUtils010::GetIPCCallCount>(m_original);
            if constexpr (requires { p->GetIPCCallCount(o); })
                return p->GetIPCCallCount(o);
            else
                return o();
        }(m_proxy);
    }

    void SetWarningMessageHook(SteamAPIWarningMessageHook_t pFunction) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUtils010::SetWarningMessageHook>(m_original);
            if constexpr (requires { p->SetWarningMessageHook(o, pFunction); })
                return p->SetWarningMessageHook(o, pFunction);
            else
                return o(pFunction);
        }(m_proxy);
    }

    bool IsOverlayEnabled() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::IsOverlayEnabled>(m_original);
            if constexpr (requires { p->IsOverlayEnabled(o); })
                return p->IsOverlayEnabled(o);
            else
                return o();
        }(m_proxy);
    }

    bool BOverlayNeedsPresent() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::BOverlayNeedsPresent>(m_original);
            if constexpr (requires { p->BOverlayNeedsPresent(o); })
                return p->BOverlayNeedsPresent(o);
            else
                return o();
        }(m_proxy);
    }

    SteamAPICall_t CheckFileSignature(const char *szFileName) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamUtils010::CheckFileSignature>(m_original);
            if constexpr (requires { p->CheckFileSignature(o, szFileName); })
                return p->CheckFileSignature(o, szFileName);
            else
                return o(szFileName);
        }(m_proxy);
    }

    bool ShowGamepadTextInput(EGamepadTextInputMode eInputMode, EGamepadTextInputLineMode eLineInputMode, const char *pchDescription, uint32 unCharMax, const char *pchExistingText) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::ShowGamepadTextInput>(m_original);
            if constexpr (requires { p->ShowGamepadTextInput(o, eInputMode, eLineInputMode, pchDescription, unCharMax, pchExistingText); })
                return p->ShowGamepadTextInput(o, eInputMode, eLineInputMode, pchDescription, unCharMax, pchExistingText);
            else
                return o(eInputMode, eLineInputMode, pchDescription, unCharMax, pchExistingText);
        }(m_proxy);
    }

    uint32 GetEnteredGamepadTextLength() override
    {
        return [&](auto p) -> uint32
        {
            auto o = MakeOrig<&ISteamUtils010::GetEnteredGamepadTextLength>(m_original);
            if constexpr (requires { p->GetEnteredGamepadTextLength(o); })
                return p->GetEnteredGamepadTextLength(o);
            else
                return o();
        }(m_proxy);
    }

    bool GetEnteredGamepadTextInput(char *pchText, uint32 cchText) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::GetEnteredGamepadTextInput>(m_original);
            if constexpr (requires { p->GetEnteredGamepadTextInput(o, pchText, cchText); })
                return p->GetEnteredGamepadTextInput(o, pchText, cchText);
            else
                return o(pchText, cchText);
        }(m_proxy);
    }

    const char *GetSteamUILanguage() override
    {
        return [&](auto p) -> const char *
        {
            auto o = MakeOrig<&ISteamUtils010::GetSteamUILanguage>(m_original);
            if constexpr (requires { p->GetSteamUILanguage(o); })
                return p->GetSteamUILanguage(o);
            else
                return o();
        }(m_proxy);
    }

    bool IsSteamRunningInVR() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::IsSteamRunningInVR>(m_original);
            if constexpr (requires { p->IsSteamRunningInVR(o); })
                return p->IsSteamRunningInVR(o);
            else
                return o();
        }(m_proxy);
    }

    void SetOverlayNotificationInset(int nHorizontalInset, int nVerticalInset) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUtils010::SetOverlayNotificationInset>(m_original);
            if constexpr (requires { p->SetOverlayNotificationInset(o, nHorizontalInset, nVerticalInset); })
                return p->SetOverlayNotificationInset(o, nHorizontalInset, nVerticalInset);
            else
                return o(nHorizontalInset, nVerticalInset);
        }(m_proxy);
    }

    bool IsSteamInBigPictureMode() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::IsSteamInBigPictureMode>(m_original);
            if constexpr (requires { p->IsSteamInBigPictureMode(o); })
                return p->IsSteamInBigPictureMode(o);
            else
                return o();
        }(m_proxy);
    }

    void StartVRDashboard() override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUtils010::StartVRDashboard>(m_original);
            if constexpr (requires { p->StartVRDashboard(o); })
                return p->StartVRDashboard(o);
            else
                return o();
        }(m_proxy);
    }

    bool IsVRHeadsetStreamingEnabled() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::IsVRHeadsetStreamingEnabled>(m_original);
            if constexpr (requires { p->IsVRHeadsetStreamingEnabled(o); })
                return p->IsVRHeadsetStreamingEnabled(o);
            else
                return o();
        }(m_proxy);
    }

    void SetVRHeadsetStreamingEnabled(bool bEnabled) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUtils010::SetVRHeadsetStreamingEnabled>(m_original);
            if constexpr (requires { p->SetVRHeadsetStreamingEnabled(o, bEnabled); })
                return p->SetVRHeadsetStreamingEnabled(o, bEnabled);
            else
                return o(bEnabled);
        }(m_proxy);
    }

    bool IsSteamChinaLauncher() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::IsSteamChinaLauncher>(m_original);
            if constexpr (requires { p->IsSteamChinaLauncher(o); })
                return p->IsSteamChinaLauncher(o);
            else
                return o();
        }(m_proxy);
    }

    bool InitFilterText(uint32 unFilterOptions) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::InitFilterText>(m_original);
            if constexpr (requires { p->InitFilterText(o, unFilterOptions); })
                return p->InitFilterText(o, unFilterOptions);
            else
                return o(unFilterOptions);
        }(m_proxy);
    }

    int FilterText(ETextFilteringContext eContext, CSteamID sourceSteamID, const char *pchInputMessage, char *pchOutFilteredText, uint32 nByteSizeOutFilteredText) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamUtils010::FilterText>(m_original);
            if constexpr (requires { p->FilterText(o, eContext, sourceSteamID, pchInputMessage, pchOutFilteredText, nByteSizeOutFilteredText); })
                return p->FilterText(o, eContext, sourceSteamID, pchInputMessage, pchOutFilteredText, nByteSizeOutFilteredText);
            else
                return o(eContext, sourceSteamID, pchInputMessage, pchOutFilteredText, nByteSizeOutFilteredText);
        }(m_proxy);
    }

    ESteamIPv6ConnectivityState GetIPv6ConnectivityState(ESteamIPv6ConnectivityProtocol eProtocol) override
    {
        return [&](auto p) -> ESteamIPv6ConnectivityState
        {
            auto o = MakeOrig<&ISteamUtils010::GetIPv6ConnectivityState>(m_original);
            if constexpr (requires { p->GetIPv6ConnectivityState(o, eProtocol); })
                return p->GetIPv6ConnectivityState(o, eProtocol);
            else
                return o(eProtocol);
        }(m_proxy);
    }

    bool IsSteamRunningOnSteamDeck() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::IsSteamRunningOnSteamDeck>(m_original);
            if constexpr (requires { p->IsSteamRunningOnSteamDeck(o); })
                return p->IsSteamRunningOnSteamDeck(o);
            else
                return o();
        }(m_proxy);
    }

    bool ShowFloatingGamepadTextInput(EFloatingGamepadTextInputMode eKeyboardMode, int nTextFieldXPosition, int nTextFieldYPosition, int nTextFieldWidth, int nTextFieldHeight) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::ShowFloatingGamepadTextInput>(m_original);
            if constexpr (requires { p->ShowFloatingGamepadTextInput(o, eKeyboardMode, nTextFieldXPosition, nTextFieldYPosition, nTextFieldWidth, nTextFieldHeight); })
                return p->ShowFloatingGamepadTextInput(o, eKeyboardMode, nTextFieldXPosition, nTextFieldYPosition, nTextFieldWidth, nTextFieldHeight);
            else
                return o(eKeyboardMode, nTextFieldXPosition, nTextFieldYPosition, nTextFieldWidth, nTextFieldHeight);
        }(m_proxy);
    }

    void SetGameLauncherMode(bool bLauncherMode) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUtils010::SetGameLauncherMode>(m_original);
            if constexpr (requires { p->SetGameLauncherMode(o, bLauncherMode); })
                return p->SetGameLauncherMode(o, bLauncherMode);
            else
                return o(bLauncherMode);
        }(m_proxy);
    }

    bool DismissFloatingGamepadTextInput() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::DismissFloatingGamepadTextInput>(m_original);
            if constexpr (requires { p->DismissFloatingGamepadTextInput(o); })
                return p->DismissFloatingGamepadTextInput(o);
            else
                return o();
        }(m_proxy);
    }

    bool DismissGamepadTextInput() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils010::DismissGamepadTextInput>(m_original);
            if constexpr (requires { p->DismissGamepadTextInput(o); })
                return p->DismissGamepadTextInput(o);
            else
                return o();
        }(m_proxy);
    }
};

#endif // STEAMUTILSPROXY010_H
