// Automatically generated by scripts/steamproxygen.py, do not modify!!!
#ifndef STEAMGAMESERVERPROXY011_H
#define STEAMGAMESERVERPROXY011_H

#include "steamproxy.h"
#include <steam_old/isteamgameserver011.h>

class SteamGameServerProxy011 final : public ISteamGameServer011
{
    ISteamGameServer011 *m_original;
    SteamGameServerProxy *m_proxy;

public:
    SteamGameServerProxy011(ISteamGameServer011 *original, SteamGameServerProxy *proxy)
        : m_original{ original }
        , m_proxy{ proxy }
    {
    }

    bool InitGameServer(uint32 unIP, uint16 usGamePort, uint16 usQueryPort, uint32 unFlags, AppId_t nGameAppId, const char *pchVersionString) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamGameServer011::InitGameServer>(m_original);
            if constexpr (requires { p->InitGameServer(o, unIP, usGamePort, usQueryPort, unFlags, nGameAppId, pchVersionString); })
                return p->InitGameServer(o, unIP, usGamePort, usQueryPort, unFlags, nGameAppId, pchVersionString);
            else
                return o(unIP, usGamePort, usQueryPort, unFlags, nGameAppId, pchVersionString);
        }(m_proxy);
    }

    void SetProduct(const char *pszProduct) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::SetProduct>(m_original);
            if constexpr (requires { p->SetProduct(o, pszProduct); })
                return p->SetProduct(o, pszProduct);
            else
                return o(pszProduct);
        }(m_proxy);
    }

    void SetGameDescription(const char *pszGameDescription) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::SetGameDescription>(m_original);
            if constexpr (requires { p->SetGameDescription(o, pszGameDescription); })
                return p->SetGameDescription(o, pszGameDescription);
            else
                return o(pszGameDescription);
        }(m_proxy);
    }

    void SetModDir(const char *pszModDir) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::SetModDir>(m_original);
            if constexpr (requires { p->SetModDir(o, pszModDir); })
                return p->SetModDir(o, pszModDir);
            else
                return o(pszModDir);
        }(m_proxy);
    }

    void SetDedicatedServer(bool bDedicated) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::SetDedicatedServer>(m_original);
            if constexpr (requires { p->SetDedicatedServer(o, bDedicated); })
                return p->SetDedicatedServer(o, bDedicated);
            else
                return o(bDedicated);
        }(m_proxy);
    }

    void LogOn(const char *pszAccountName, const char *pszPassword) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::LogOn>(m_original);
            if constexpr (requires { p->LogOn(o, pszAccountName, pszPassword); })
                return p->LogOn(o, pszAccountName, pszPassword);
            else
                return o(pszAccountName, pszPassword);
        }(m_proxy);
    }

    void LogOnAnonymous() override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::LogOnAnonymous>(m_original);
            if constexpr (requires { p->LogOnAnonymous(o); })
                return p->LogOnAnonymous(o);
            else
                return o();
        }(m_proxy);
    }

    void LogOff() override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::LogOff>(m_original);
            if constexpr (requires { p->LogOff(o); })
                return p->LogOff(o);
            else
                return o();
        }(m_proxy);
    }

    bool BLoggedOn() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamGameServer011::BLoggedOn>(m_original);
            if constexpr (requires { p->BLoggedOn(o); })
                return p->BLoggedOn(o);
            else
                return o();
        }(m_proxy);
    }

    bool BSecure() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamGameServer011::BSecure>(m_original);
            if constexpr (requires { p->BSecure(o); })
                return p->BSecure(o);
            else
                return o();
        }(m_proxy);
    }

    CSteamID GetSteamID() override
    {
        return [&](auto p) -> CSteamID
        {
            auto o = MakeOrig<&ISteamGameServer011::GetSteamID>(m_original);
            if constexpr (requires { p->GetSteamID(o); })
                return p->GetSteamID(o);
            else
                return o();
        }(m_proxy);
    }

    bool WasRestartRequested() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamGameServer011::WasRestartRequested>(m_original);
            if constexpr (requires { p->WasRestartRequested(o); })
                return p->WasRestartRequested(o);
            else
                return o();
        }(m_proxy);
    }

    void SetMaxPlayerCount(int cPlayersMax) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::SetMaxPlayerCount>(m_original);
            if constexpr (requires { p->SetMaxPlayerCount(o, cPlayersMax); })
                return p->SetMaxPlayerCount(o, cPlayersMax);
            else
                return o(cPlayersMax);
        }(m_proxy);
    }

    void SetBotPlayerCount(int cBotplayers) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::SetBotPlayerCount>(m_original);
            if constexpr (requires { p->SetBotPlayerCount(o, cBotplayers); })
                return p->SetBotPlayerCount(o, cBotplayers);
            else
                return o(cBotplayers);
        }(m_proxy);
    }

    void SetServerName(const char *pszServerName) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::SetServerName>(m_original);
            if constexpr (requires { p->SetServerName(o, pszServerName); })
                return p->SetServerName(o, pszServerName);
            else
                return o(pszServerName);
        }(m_proxy);
    }

    void SetMapName(const char *pszMapName) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::SetMapName>(m_original);
            if constexpr (requires { p->SetMapName(o, pszMapName); })
                return p->SetMapName(o, pszMapName);
            else
                return o(pszMapName);
        }(m_proxy);
    }

    void SetPasswordProtected(bool bPasswordProtected) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::SetPasswordProtected>(m_original);
            if constexpr (requires { p->SetPasswordProtected(o, bPasswordProtected); })
                return p->SetPasswordProtected(o, bPasswordProtected);
            else
                return o(bPasswordProtected);
        }(m_proxy);
    }

    void SetSpectatorPort(uint16 unSpectatorPort) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::SetSpectatorPort>(m_original);
            if constexpr (requires { p->SetSpectatorPort(o, unSpectatorPort); })
                return p->SetSpectatorPort(o, unSpectatorPort);
            else
                return o(unSpectatorPort);
        }(m_proxy);
    }

    void SetSpectatorServerName(const char *pszSpectatorServerName) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::SetSpectatorServerName>(m_original);
            if constexpr (requires { p->SetSpectatorServerName(o, pszSpectatorServerName); })
                return p->SetSpectatorServerName(o, pszSpectatorServerName);
            else
                return o(pszSpectatorServerName);
        }(m_proxy);
    }

    void ClearAllKeyValues() override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::ClearAllKeyValues>(m_original);
            if constexpr (requires { p->ClearAllKeyValues(o); })
                return p->ClearAllKeyValues(o);
            else
                return o();
        }(m_proxy);
    }

    void SetKeyValue(const char *pKey, const char *pValue) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::SetKeyValue>(m_original);
            if constexpr (requires { p->SetKeyValue(o, pKey, pValue); })
                return p->SetKeyValue(o, pKey, pValue);
            else
                return o(pKey, pValue);
        }(m_proxy);
    }

    void SetGameTags(const char *pchGameTags) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::SetGameTags>(m_original);
            if constexpr (requires { p->SetGameTags(o, pchGameTags); })
                return p->SetGameTags(o, pchGameTags);
            else
                return o(pchGameTags);
        }(m_proxy);
    }

    void SetGameData(const char *pchGameData) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::SetGameData>(m_original);
            if constexpr (requires { p->SetGameData(o, pchGameData); })
                return p->SetGameData(o, pchGameData);
            else
                return o(pchGameData);
        }(m_proxy);
    }

    void SetRegion(const char *pszRegion) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::SetRegion>(m_original);
            if constexpr (requires { p->SetRegion(o, pszRegion); })
                return p->SetRegion(o, pszRegion);
            else
                return o(pszRegion);
        }(m_proxy);
    }

    bool SendUserConnectAndAuthenticate(uint32 unIPClient, const void *pvAuthBlob, uint32 cubAuthBlobSize, CSteamID *pSteamIDUser) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamGameServer011::SendUserConnectAndAuthenticate>(m_original);
            if constexpr (requires { p->SendUserConnectAndAuthenticate(o, unIPClient, pvAuthBlob, cubAuthBlobSize, pSteamIDUser); })
                return p->SendUserConnectAndAuthenticate(o, unIPClient, pvAuthBlob, cubAuthBlobSize, pSteamIDUser);
            else
                return o(unIPClient, pvAuthBlob, cubAuthBlobSize, pSteamIDUser);
        }(m_proxy);
    }

    CSteamID CreateUnauthenticatedUserConnection() override
    {
        return [&](auto p) -> CSteamID
        {
            auto o = MakeOrig<&ISteamGameServer011::CreateUnauthenticatedUserConnection>(m_original);
            if constexpr (requires { p->CreateUnauthenticatedUserConnection(o); })
                return p->CreateUnauthenticatedUserConnection(o);
            else
                return o();
        }(m_proxy);
    }

    void SendUserDisconnect(CSteamID steamIDUser) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::SendUserDisconnect>(m_original);
            if constexpr (requires { p->SendUserDisconnect(o, steamIDUser); })
                return p->SendUserDisconnect(o, steamIDUser);
            else
                return o(steamIDUser);
        }(m_proxy);
    }

    bool BUpdateUserData(CSteamID steamIDUser, const char *pchPlayerName, uint32 uScore) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamGameServer011::BUpdateUserData>(m_original);
            if constexpr (requires { p->BUpdateUserData(o, steamIDUser, pchPlayerName, uScore); })
                return p->BUpdateUserData(o, steamIDUser, pchPlayerName, uScore);
            else
                return o(steamIDUser, pchPlayerName, uScore);
        }(m_proxy);
    }

    HAuthTicket GetAuthSessionTicket(void *pTicket, int cbMaxTicket, uint32 *pcbTicket) override
    {
        return [&](auto p) -> HAuthTicket
        {
            auto o = MakeOrig<&ISteamGameServer011::GetAuthSessionTicket>(m_original);
            if constexpr (requires { p->GetAuthSessionTicket(o, pTicket, cbMaxTicket, pcbTicket); })
                return p->GetAuthSessionTicket(o, pTicket, cbMaxTicket, pcbTicket);
            else
                return o(pTicket, cbMaxTicket, pcbTicket);
        }(m_proxy);
    }

    EBeginAuthSessionResult BeginAuthSession(const void *pAuthTicket, int cbAuthTicket, CSteamID steamID) override
    {
        return [&](auto p) -> EBeginAuthSessionResult
        {
            auto o = MakeOrig<&ISteamGameServer011::BeginAuthSession>(m_original);
            if constexpr (requires { p->BeginAuthSession(o, pAuthTicket, cbAuthTicket, steamID); })
                return p->BeginAuthSession(o, pAuthTicket, cbAuthTicket, steamID);
            else
                return o(pAuthTicket, cbAuthTicket, steamID);
        }(m_proxy);
    }

    void EndAuthSession(CSteamID steamID) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::EndAuthSession>(m_original);
            if constexpr (requires { p->EndAuthSession(o, steamID); })
                return p->EndAuthSession(o, steamID);
            else
                return o(steamID);
        }(m_proxy);
    }

    void CancelAuthTicket(HAuthTicket hAuthTicket) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::CancelAuthTicket>(m_original);
            if constexpr (requires { p->CancelAuthTicket(o, hAuthTicket); })
                return p->CancelAuthTicket(o, hAuthTicket);
            else
                return o(hAuthTicket);
        }(m_proxy);
    }

    EUserHasLicenseForAppResult UserHasLicenseForApp(CSteamID steamID, AppId_t appID) override
    {
        return [&](auto p) -> EUserHasLicenseForAppResult
        {
            auto o = MakeOrig<&ISteamGameServer011::UserHasLicenseForApp>(m_original);
            if constexpr (requires { p->UserHasLicenseForApp(o, steamID, appID); })
                return p->UserHasLicenseForApp(o, steamID, appID);
            else
                return o(steamID, appID);
        }(m_proxy);
    }

    bool RequestUserGroupStatus(CSteamID steamIDUser, CSteamID steamIDGroup) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamGameServer011::RequestUserGroupStatus>(m_original);
            if constexpr (requires { p->RequestUserGroupStatus(o, steamIDUser, steamIDGroup); })
                return p->RequestUserGroupStatus(o, steamIDUser, steamIDGroup);
            else
                return o(steamIDUser, steamIDGroup);
        }(m_proxy);
    }

    void GetGameplayStats() override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::GetGameplayStats>(m_original);
            if constexpr (requires { p->GetGameplayStats(o); })
                return p->GetGameplayStats(o);
            else
                return o();
        }(m_proxy);
    }

    SteamAPICall_t GetServerReputation() override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamGameServer011::GetServerReputation>(m_original);
            if constexpr (requires { p->GetServerReputation(o); })
                return p->GetServerReputation(o);
            else
                return o();
        }(m_proxy);
    }

    uint32 GetPublicIP() override
    {
        return [&](auto p) -> uint32
        {
            auto o = MakeOrig<&ISteamGameServer011::GetPublicIP>(m_original);
            if constexpr (requires { p->GetPublicIP(o); })
                return p->GetPublicIP(o);
            else
                return o();
        }(m_proxy);
    }

    bool HandleIncomingPacket(const void *pData, int cbData, uint32 srcIP, uint16 srcPort) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamGameServer011::HandleIncomingPacket>(m_original);
            if constexpr (requires { p->HandleIncomingPacket(o, pData, cbData, srcIP, srcPort); })
                return p->HandleIncomingPacket(o, pData, cbData, srcIP, srcPort);
            else
                return o(pData, cbData, srcIP, srcPort);
        }(m_proxy);
    }

    int GetNextOutgoingPacket(void *pOut, int cbMaxOut, uint32 *pNetAdr, uint16 *pPort) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamGameServer011::GetNextOutgoingPacket>(m_original);
            if constexpr (requires { p->GetNextOutgoingPacket(o, pOut, cbMaxOut, pNetAdr, pPort); })
                return p->GetNextOutgoingPacket(o, pOut, cbMaxOut, pNetAdr, pPort);
            else
                return o(pOut, cbMaxOut, pNetAdr, pPort);
        }(m_proxy);
    }

    void EnableHeartbeats(bool bActive) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::EnableHeartbeats>(m_original);
            if constexpr (requires { p->EnableHeartbeats(o, bActive); })
                return p->EnableHeartbeats(o, bActive);
            else
                return o(bActive);
        }(m_proxy);
    }

    void SetHeartbeatInterval(int iHeartbeatInterval) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::SetHeartbeatInterval>(m_original);
            if constexpr (requires { p->SetHeartbeatInterval(o, iHeartbeatInterval); })
                return p->SetHeartbeatInterval(o, iHeartbeatInterval);
            else
                return o(iHeartbeatInterval);
        }(m_proxy);
    }

    void ForceHeartbeat() override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer011::ForceHeartbeat>(m_original);
            if constexpr (requires { p->ForceHeartbeat(o); })
                return p->ForceHeartbeat(o);
            else
                return o();
        }(m_proxy);
    }

    SteamAPICall_t AssociateWithClan(CSteamID steamIDClan) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamGameServer011::AssociateWithClan>(m_original);
            if constexpr (requires { p->AssociateWithClan(o, steamIDClan); })
                return p->AssociateWithClan(o, steamIDClan);
            else
                return o(steamIDClan);
        }(m_proxy);
    }

    SteamAPICall_t ComputeNewPlayerCompatibility(CSteamID steamIDNewPlayer) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamGameServer011::ComputeNewPlayerCompatibility>(m_original);
            if constexpr (requires { p->ComputeNewPlayerCompatibility(o, steamIDNewPlayer); })
                return p->ComputeNewPlayerCompatibility(o, steamIDNewPlayer);
            else
                return o(steamIDNewPlayer);
        }(m_proxy);
    }
};

#endif // STEAMGAMESERVERPROXY011_H
