// Automatically generated by scripts/steamproxygen.py, do not modify!!!
#ifndef STEAMCLIENTPROXY020_H
#define STEAMCLIENTPROXY020_H

#include "steamproxy.h"
#include <steam_old/isteamclient020.h>

class SteamClientProxy020 final : public ISteamClient020
{
    ISteamClient020 *m_original;
    SteamClientProxy *m_proxy;

public:
    SteamClientProxy020(ISteamClient020 *original, SteamClientProxy *proxy)
        : m_original{ original }
        , m_proxy{ proxy }
    {
    }

    HSteamPipe CreateSteamPipe() override
    {
        return [&](auto p) -> HSteamPipe
        {
            auto o = MakeOrig<&ISteamClient020::CreateSteamPipe>(m_original);
            if constexpr (requires { p->CreateSteamPipe(o); })
                return p->CreateSteamPipe(o);
            else
                return o();
        }(m_proxy);
    }

    bool BReleaseSteamPipe(HSteamPipe hSteamPipe) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamClient020::BReleaseSteamPipe>(m_original);
            if constexpr (requires { p->BReleaseSteamPipe(o, hSteamPipe); })
                return p->BReleaseSteamPipe(o, hSteamPipe);
            else
                return o(hSteamPipe);
        }(m_proxy);
    }

    HSteamUser ConnectToGlobalUser(HSteamPipe hSteamPipe) override
    {
        return [&](auto p) -> HSteamUser
        {
            auto o = MakeOrig<&ISteamClient020::ConnectToGlobalUser>(m_original);
            if constexpr (requires { p->ConnectToGlobalUser(o, hSteamPipe); })
                return p->ConnectToGlobalUser(o, hSteamPipe);
            else
                return o(hSteamPipe);
        }(m_proxy);
    }

    HSteamUser CreateLocalUser(HSteamPipe *phSteamPipe, EAccountType eAccountType) override
    {
        return [&](auto p) -> HSteamUser
        {
            auto o = MakeOrig<&ISteamClient020::CreateLocalUser>(m_original);
            if constexpr (requires { p->CreateLocalUser(o, phSteamPipe, eAccountType); })
                return p->CreateLocalUser(o, phSteamPipe, eAccountType);
            else
                return o(phSteamPipe, eAccountType);
        }(m_proxy);
    }

    void ReleaseUser(HSteamPipe hSteamPipe, HSteamUser hUser) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamClient020::ReleaseUser>(m_original);
            if constexpr (requires { p->ReleaseUser(o, hSteamPipe, hUser); })
                return p->ReleaseUser(o, hSteamPipe, hUser);
            else
                return o(hSteamPipe, hUser);
        }(m_proxy);
    }

    ISteamUser *GetISteamUser(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamUser *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamUser>(m_original);
            if constexpr (requires { p->GetISteamUser(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamUser(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamGameServer *GetISteamGameServer(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamGameServer *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamGameServer>(m_original);
            if constexpr (requires { p->GetISteamGameServer(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamGameServer(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    void SetLocalIPBinding(const SteamIPAddress_t &unIP, uint16 usPort) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamClient020::SetLocalIPBinding>(m_original);
            if constexpr (requires { p->SetLocalIPBinding(o, unIP, usPort); })
                return p->SetLocalIPBinding(o, unIP, usPort);
            else
                return o(unIP, usPort);
        }(m_proxy);
    }

    ISteamFriends *GetISteamFriends(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamFriends *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamFriends>(m_original);
            if constexpr (requires { p->GetISteamFriends(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamFriends(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamUtils *GetISteamUtils(HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamUtils *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamUtils>(m_original);
            if constexpr (requires { p->GetISteamUtils(o, hSteamPipe, pchVersion); })
                return p->GetISteamUtils(o, hSteamPipe, pchVersion);
            else
                return o(hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamMatchmaking *GetISteamMatchmaking(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamMatchmaking *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamMatchmaking>(m_original);
            if constexpr (requires { p->GetISteamMatchmaking(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamMatchmaking(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamMatchmakingServers *GetISteamMatchmakingServers(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamMatchmakingServers *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamMatchmakingServers>(m_original);
            if constexpr (requires { p->GetISteamMatchmakingServers(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamMatchmakingServers(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    void *GetISteamGenericInterface(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> void *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamGenericInterface>(m_original);
            if constexpr (requires { p->GetISteamGenericInterface(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamGenericInterface(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamUserStats *GetISteamUserStats(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamUserStats *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamUserStats>(m_original);
            if constexpr (requires { p->GetISteamUserStats(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamUserStats(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamGameServerStats *GetISteamGameServerStats(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamGameServerStats *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamGameServerStats>(m_original);
            if constexpr (requires { p->GetISteamGameServerStats(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamGameServerStats(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamApps *GetISteamApps(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamApps *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamApps>(m_original);
            if constexpr (requires { p->GetISteamApps(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamApps(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamNetworking *GetISteamNetworking(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamNetworking *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamNetworking>(m_original);
            if constexpr (requires { p->GetISteamNetworking(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamNetworking(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamRemoteStorage *GetISteamRemoteStorage(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamRemoteStorage *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamRemoteStorage>(m_original);
            if constexpr (requires { p->GetISteamRemoteStorage(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamRemoteStorage(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamScreenshots *GetISteamScreenshots(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamScreenshots *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamScreenshots>(m_original);
            if constexpr (requires { p->GetISteamScreenshots(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamScreenshots(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamGameSearch *GetISteamGameSearch(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamGameSearch *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamGameSearch>(m_original);
            if constexpr (requires { p->GetISteamGameSearch(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamGameSearch(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    void RunFrame() override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamClient020::RunFrame>(m_original);
            if constexpr (requires { p->RunFrame(o); })
                return p->RunFrame(o);
            else
                return o();
        }(m_proxy);
    }

    uint32 GetIPCCallCount() override
    {
        return [&](auto p) -> uint32
        {
            auto o = MakeOrig<&ISteamClient020::GetIPCCallCount>(m_original);
            if constexpr (requires { p->GetIPCCallCount(o); })
                return p->GetIPCCallCount(o);
            else
                return o();
        }(m_proxy);
    }

    void SetWarningMessageHook(SteamAPIWarningMessageHook_t pFunction) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamClient020::SetWarningMessageHook>(m_original);
            if constexpr (requires { p->SetWarningMessageHook(o, pFunction); })
                return p->SetWarningMessageHook(o, pFunction);
            else
                return o(pFunction);
        }(m_proxy);
    }

    bool BShutdownIfAllPipesClosed() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamClient020::BShutdownIfAllPipesClosed>(m_original);
            if constexpr (requires { p->BShutdownIfAllPipesClosed(o); })
                return p->BShutdownIfAllPipesClosed(o);
            else
                return o();
        }(m_proxy);
    }

    ISteamHTTP *GetISteamHTTP(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamHTTP *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamHTTP>(m_original);
            if constexpr (requires { p->GetISteamHTTP(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamHTTP(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    void *DEPRECATED_GetISteamUnifiedMessages(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> void *
        {
            auto o = MakeOrig<&ISteamClient020::DEPRECATED_GetISteamUnifiedMessages>(m_original);
            if constexpr (requires { p->DEPRECATED_GetISteamUnifiedMessages(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->DEPRECATED_GetISteamUnifiedMessages(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamController *GetISteamController(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamController *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamController>(m_original);
            if constexpr (requires { p->GetISteamController(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamController(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamUGC *GetISteamUGC(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamUGC *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamUGC>(m_original);
            if constexpr (requires { p->GetISteamUGC(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamUGC(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamAppList *GetISteamAppList(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamAppList *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamAppList>(m_original);
            if constexpr (requires { p->GetISteamAppList(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamAppList(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamMusic *GetISteamMusic(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamMusic *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamMusic>(m_original);
            if constexpr (requires { p->GetISteamMusic(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamMusic(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamMusicRemote *GetISteamMusicRemote(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamMusicRemote *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamMusicRemote>(m_original);
            if constexpr (requires { p->GetISteamMusicRemote(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamMusicRemote(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamHTMLSurface *GetISteamHTMLSurface(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamHTMLSurface *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamHTMLSurface>(m_original);
            if constexpr (requires { p->GetISteamHTMLSurface(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamHTMLSurface(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    void DEPRECATED_Set_SteamAPI_CPostAPIResultInProcess(TypeIdentityT<void (*)()> a0) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamClient020::DEPRECATED_Set_SteamAPI_CPostAPIResultInProcess>(m_original);
            if constexpr (requires { p->DEPRECATED_Set_SteamAPI_CPostAPIResultInProcess(o, a0); })
                return p->DEPRECATED_Set_SteamAPI_CPostAPIResultInProcess(o, a0);
            else
                return o(a0);
        }(m_proxy);
    }

    void DEPRECATED_Remove_SteamAPI_CPostAPIResultInProcess(TypeIdentityT<void (*)()> a0) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamClient020::DEPRECATED_Remove_SteamAPI_CPostAPIResultInProcess>(m_original);
            if constexpr (requires { p->DEPRECATED_Remove_SteamAPI_CPostAPIResultInProcess(o, a0); })
                return p->DEPRECATED_Remove_SteamAPI_CPostAPIResultInProcess(o, a0);
            else
                return o(a0);
        }(m_proxy);
    }

    void Set_SteamAPI_CCheckCallbackRegisteredInProcess(SteamAPI_CheckCallbackRegistered_t func) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamClient020::Set_SteamAPI_CCheckCallbackRegisteredInProcess>(m_original);
            if constexpr (requires { p->Set_SteamAPI_CCheckCallbackRegisteredInProcess(o, func); })
                return p->Set_SteamAPI_CCheckCallbackRegisteredInProcess(o, func);
            else
                return o(func);
        }(m_proxy);
    }

    ISteamInventory *GetISteamInventory(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamInventory *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamInventory>(m_original);
            if constexpr (requires { p->GetISteamInventory(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamInventory(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamVideo *GetISteamVideo(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamVideo *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamVideo>(m_original);
            if constexpr (requires { p->GetISteamVideo(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamVideo(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamParentalSettings *GetISteamParentalSettings(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamParentalSettings *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamParentalSettings>(m_original);
            if constexpr (requires { p->GetISteamParentalSettings(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamParentalSettings(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamInput *GetISteamInput(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamInput *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamInput>(m_original);
            if constexpr (requires { p->GetISteamInput(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamInput(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamParties *GetISteamParties(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamParties *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamParties>(m_original);
            if constexpr (requires { p->GetISteamParties(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamParties(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamRemotePlay *GetISteamRemotePlay(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamRemotePlay *
        {
            auto o = MakeOrig<&ISteamClient020::GetISteamRemotePlay>(m_original);
            if constexpr (requires { p->GetISteamRemotePlay(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamRemotePlay(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    void DestroyAllInterfaces() override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamClient020::DestroyAllInterfaces>(m_original);
            if constexpr (requires { p->DestroyAllInterfaces(o); })
                return p->DestroyAllInterfaces(o);
            else
                return o();
        }(m_proxy);
    }
};

#endif // STEAMCLIENTPROXY020_H
