// Automatically generated by scripts/steamproxygen.py, do not modify!!!
#ifndef STEAMMATCHMAKINGSERVERSPROXY002_H
#define STEAMMATCHMAKINGSERVERSPROXY002_H

#include "steamproxy.h"
#include <steam_old/isteammatchmakingservers002.h>

class SteamMatchmakingServersProxy002 final : public ISteamMatchmakingServers002
{
    ISteamMatchmakingServers002 *m_original;
    SteamMatchmakingServersProxy *m_proxy;

public:
    SteamMatchmakingServersProxy002(ISteamMatchmakingServers002 *original, SteamMatchmakingServersProxy *proxy)
        : m_original{ original }
        , m_proxy{ proxy }
    {
    }

    HServerListRequest RequestInternetServerList(AppId_t iApp, MatchMakingKeyValuePair_t **ppchFilters, uint32 nFilters, ISteamMatchmakingServerListResponse *pRequestServersResponse) override
    {
        return [&](auto p) -> HServerListRequest
        {
            auto o = MakeOrig<&ISteamMatchmakingServers002::RequestInternetServerList>(m_original);
            if constexpr (requires { p->RequestInternetServerList(o, iApp, ppchFilters, nFilters, pRequestServersResponse); })
                return p->RequestInternetServerList(o, iApp, ppchFilters, nFilters, pRequestServersResponse);
            else
                return o(iApp, ppchFilters, nFilters, pRequestServersResponse);
        }(m_proxy);
    }

    HServerListRequest RequestLANServerList(AppId_t iApp, ISteamMatchmakingServerListResponse *pRequestServersResponse) override
    {
        return [&](auto p) -> HServerListRequest
        {
            auto o = MakeOrig<&ISteamMatchmakingServers002::RequestLANServerList>(m_original);
            if constexpr (requires { p->RequestLANServerList(o, iApp, pRequestServersResponse); })
                return p->RequestLANServerList(o, iApp, pRequestServersResponse);
            else
                return o(iApp, pRequestServersResponse);
        }(m_proxy);
    }

    HServerListRequest RequestFriendsServerList(AppId_t iApp, MatchMakingKeyValuePair_t **ppchFilters, uint32 nFilters, ISteamMatchmakingServerListResponse *pRequestServersResponse) override
    {
        return [&](auto p) -> HServerListRequest
        {
            auto o = MakeOrig<&ISteamMatchmakingServers002::RequestFriendsServerList>(m_original);
            if constexpr (requires { p->RequestFriendsServerList(o, iApp, ppchFilters, nFilters, pRequestServersResponse); })
                return p->RequestFriendsServerList(o, iApp, ppchFilters, nFilters, pRequestServersResponse);
            else
                return o(iApp, ppchFilters, nFilters, pRequestServersResponse);
        }(m_proxy);
    }

    HServerListRequest RequestFavoritesServerList(AppId_t iApp, MatchMakingKeyValuePair_t **ppchFilters, uint32 nFilters, ISteamMatchmakingServerListResponse *pRequestServersResponse) override
    {
        return [&](auto p) -> HServerListRequest
        {
            auto o = MakeOrig<&ISteamMatchmakingServers002::RequestFavoritesServerList>(m_original);
            if constexpr (requires { p->RequestFavoritesServerList(o, iApp, ppchFilters, nFilters, pRequestServersResponse); })
                return p->RequestFavoritesServerList(o, iApp, ppchFilters, nFilters, pRequestServersResponse);
            else
                return o(iApp, ppchFilters, nFilters, pRequestServersResponse);
        }(m_proxy);
    }

    HServerListRequest RequestHistoryServerList(AppId_t iApp, MatchMakingKeyValuePair_t **ppchFilters, uint32 nFilters, ISteamMatchmakingServerListResponse *pRequestServersResponse) override
    {
        return [&](auto p) -> HServerListRequest
        {
            auto o = MakeOrig<&ISteamMatchmakingServers002::RequestHistoryServerList>(m_original);
            if constexpr (requires { p->RequestHistoryServerList(o, iApp, ppchFilters, nFilters, pRequestServersResponse); })
                return p->RequestHistoryServerList(o, iApp, ppchFilters, nFilters, pRequestServersResponse);
            else
                return o(iApp, ppchFilters, nFilters, pRequestServersResponse);
        }(m_proxy);
    }

    HServerListRequest RequestSpectatorServerList(AppId_t iApp, MatchMakingKeyValuePair_t **ppchFilters, uint32 nFilters, ISteamMatchmakingServerListResponse *pRequestServersResponse) override
    {
        return [&](auto p) -> HServerListRequest
        {
            auto o = MakeOrig<&ISteamMatchmakingServers002::RequestSpectatorServerList>(m_original);
            if constexpr (requires { p->RequestSpectatorServerList(o, iApp, ppchFilters, nFilters, pRequestServersResponse); })
                return p->RequestSpectatorServerList(o, iApp, ppchFilters, nFilters, pRequestServersResponse);
            else
                return o(iApp, ppchFilters, nFilters, pRequestServersResponse);
        }(m_proxy);
    }

    void ReleaseRequest(HServerListRequest hServerListRequest) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamMatchmakingServers002::ReleaseRequest>(m_original);
            if constexpr (requires { p->ReleaseRequest(o, hServerListRequest); })
                return p->ReleaseRequest(o, hServerListRequest);
            else
                return o(hServerListRequest);
        }(m_proxy);
    }

    gameserveritem_t *GetServerDetails(HServerListRequest hRequest, int iServer) override
    {
        return [&](auto p) -> gameserveritem_t *
        {
            auto o = MakeOrig<&ISteamMatchmakingServers002::GetServerDetails>(m_original);
            if constexpr (requires { p->GetServerDetails(o, hRequest, iServer); })
                return p->GetServerDetails(o, hRequest, iServer);
            else
                return o(hRequest, iServer);
        }(m_proxy);
    }

    void CancelQuery(HServerListRequest hRequest) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamMatchmakingServers002::CancelQuery>(m_original);
            if constexpr (requires { p->CancelQuery(o, hRequest); })
                return p->CancelQuery(o, hRequest);
            else
                return o(hRequest);
        }(m_proxy);
    }

    void RefreshQuery(HServerListRequest hRequest) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamMatchmakingServers002::RefreshQuery>(m_original);
            if constexpr (requires { p->RefreshQuery(o, hRequest); })
                return p->RefreshQuery(o, hRequest);
            else
                return o(hRequest);
        }(m_proxy);
    }

    bool IsRefreshing(HServerListRequest hRequest) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamMatchmakingServers002::IsRefreshing>(m_original);
            if constexpr (requires { p->IsRefreshing(o, hRequest); })
                return p->IsRefreshing(o, hRequest);
            else
                return o(hRequest);
        }(m_proxy);
    }

    int GetServerCount(HServerListRequest hRequest) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamMatchmakingServers002::GetServerCount>(m_original);
            if constexpr (requires { p->GetServerCount(o, hRequest); })
                return p->GetServerCount(o, hRequest);
            else
                return o(hRequest);
        }(m_proxy);
    }

    void RefreshServer(HServerListRequest hRequest, int iServer) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamMatchmakingServers002::RefreshServer>(m_original);
            if constexpr (requires { p->RefreshServer(o, hRequest, iServer); })
                return p->RefreshServer(o, hRequest, iServer);
            else
                return o(hRequest, iServer);
        }(m_proxy);
    }

    HServerQuery PingServer(uint32 unIP, uint16 usPort, ISteamMatchmakingPingResponse *pRequestServersResponse) override
    {
        return [&](auto p) -> HServerQuery
        {
            auto o = MakeOrig<&ISteamMatchmakingServers002::PingServer>(m_original);
            if constexpr (requires { p->PingServer(o, unIP, usPort, pRequestServersResponse); })
                return p->PingServer(o, unIP, usPort, pRequestServersResponse);
            else
                return o(unIP, usPort, pRequestServersResponse);
        }(m_proxy);
    }

    HServerQuery PlayerDetails(uint32 unIP, uint16 usPort, ISteamMatchmakingPlayersResponse *pRequestServersResponse) override
    {
        return [&](auto p) -> HServerQuery
        {
            auto o = MakeOrig<&ISteamMatchmakingServers002::PlayerDetails>(m_original);
            if constexpr (requires { p->PlayerDetails(o, unIP, usPort, pRequestServersResponse); })
                return p->PlayerDetails(o, unIP, usPort, pRequestServersResponse);
            else
                return o(unIP, usPort, pRequestServersResponse);
        }(m_proxy);
    }

    HServerQuery ServerRules(uint32 unIP, uint16 usPort, ISteamMatchmakingRulesResponse *pRequestServersResponse) override
    {
        return [&](auto p) -> HServerQuery
        {
            auto o = MakeOrig<&ISteamMatchmakingServers002::ServerRules>(m_original);
            if constexpr (requires { p->ServerRules(o, unIP, usPort, pRequestServersResponse); })
                return p->ServerRules(o, unIP, usPort, pRequestServersResponse);
            else
                return o(unIP, usPort, pRequestServersResponse);
        }(m_proxy);
    }

    void CancelServerQuery(HServerQuery hServerQuery) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamMatchmakingServers002::CancelServerQuery>(m_original);
            if constexpr (requires { p->CancelServerQuery(o, hServerQuery); })
                return p->CancelServerQuery(o, hServerQuery);
            else
                return o(hServerQuery);
        }(m_proxy);
    }
};

#endif // STEAMMATCHMAKINGSERVERSPROXY002_H
