// Automatically generated by scripts/steamproxygen.py, do not modify!!!
#ifndef STEAMGAMECOORDINATORPROXY001_H
#define STEAMGAMECOORDINATORPROXY001_H

#include "steamproxy.h"
#include <steam_old/isteamgamecoordinator001.h>

class SteamGameCoordinatorProxy001 final : public ISteamGameCoordinator001
{
    ISteamGameCoordinator001 *m_original;
    SteamGameCoordinatorProxy *m_proxy;

public:
    SteamGameCoordinatorProxy001(ISteamGameCoordinator001 *original, SteamGameCoordinatorProxy *proxy)
        : m_original{ original }
        , m_proxy{ proxy }
    {
    }

    EGCResults SendMessage(uint32 unMsgType, const void *pubData, uint32 cubData) override
    {
        return [&](auto p) -> EGCResults
        {
            auto o = MakeOrig<&ISteamGameCoordinator001::SendMessage>(m_original);
            if constexpr (requires { p->SendMessage(o, unMsgType, pubData, cubData); })
                return p->SendMessage(o, unMsgType, pubData, cubData);
            else
                return o(unMsgType, pubData, cubData);
        }(m_proxy);
    }

    bool IsMessageAvailable(uint32 *pcubMsgSize) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamGameCoordinator001::IsMessageAvailable>(m_original);
            if constexpr (requires { p->IsMessageAvailable(o, pcubMsgSize); })
                return p->IsMessageAvailable(o, pcubMsgSize);
            else
                return o(pcubMsgSize);
        }(m_proxy);
    }

    EGCResults RetrieveMessage(uint32 *punMsgType, void *pubDest, uint32 cubDest, uint32 *pcubMsgSize) override
    {
        return [&](auto p) -> EGCResults
        {
            auto o = MakeOrig<&ISteamGameCoordinator001::RetrieveMessage>(m_original);
            if constexpr (requires { p->RetrieveMessage(o, punMsgType, pubDest, cubDest, pcubMsgSize); })
                return p->RetrieveMessage(o, punMsgType, pubDest, cubDest, pcubMsgSize);
            else
                return o(punMsgType, pubDest, cubDest, pcubMsgSize);
        }(m_proxy);
    }
};

#endif // STEAMGAMECOORDINATORPROXY001_H
