// Automatically generated by scripts/steamproxygen.py, do not modify!!!
#ifndef STEAMUSERPROXY021_H
#define STEAMUSERPROXY021_H

#include "steamproxy.h"
#include <steam_old/isteamuser021.h>

class SteamUserProxy021 final : public ISteamUser021
{
    ISteamUser021 *m_original;
    SteamUserProxy *m_proxy;

public:
    SteamUserProxy021(ISteamUser021 *original, SteamUserProxy *proxy)
        : m_original{ original }
        , m_proxy{ proxy }
    {
    }

    HSteamUser GetHSteamUser() override
    {
        return [&](auto p) -> HSteamUser
        {
            auto o = MakeOrig<&ISteamUser021::GetHSteamUser>(m_original);
            if constexpr (requires { p->GetHSteamUser(o); })
                return p->GetHSteamUser(o);
            else
                return o();
        }(m_proxy);
    }

    bool BLoggedOn() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUser021::BLoggedOn>(m_original);
            if constexpr (requires { p->BLoggedOn(o); })
                return p->BLoggedOn(o);
            else
                return o();
        }(m_proxy);
    }

    CSteamID GetSteamID() override
    {
        return [&](auto p) -> CSteamID
        {
            auto o = MakeOrig<&ISteamUser021::GetSteamID>(m_original);
            if constexpr (requires { p->GetSteamID(o); })
                return p->GetSteamID(o);
            else
                return o();
        }(m_proxy);
    }

    int InitiateGameConnection_DEPRECATED(void *pAuthBlob, int cbMaxAuthBlob, CSteamID steamIDGameServer, uint32 unIPServer, uint16 usPortServer, bool bSecure) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamUser021::InitiateGameConnection_DEPRECATED>(m_original);
            if constexpr (requires { p->InitiateGameConnection_DEPRECATED(o, pAuthBlob, cbMaxAuthBlob, steamIDGameServer, unIPServer, usPortServer, bSecure); })
                return p->InitiateGameConnection_DEPRECATED(o, pAuthBlob, cbMaxAuthBlob, steamIDGameServer, unIPServer, usPortServer, bSecure);
            else
                return o(pAuthBlob, cbMaxAuthBlob, steamIDGameServer, unIPServer, usPortServer, bSecure);
        }(m_proxy);
    }

    void TerminateGameConnection_DEPRECATED(uint32 unIPServer, uint16 usPortServer) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUser021::TerminateGameConnection_DEPRECATED>(m_original);
            if constexpr (requires { p->TerminateGameConnection_DEPRECATED(o, unIPServer, usPortServer); })
                return p->TerminateGameConnection_DEPRECATED(o, unIPServer, usPortServer);
            else
                return o(unIPServer, usPortServer);
        }(m_proxy);
    }

    void TrackAppUsageEvent(CGameID gameID, int eAppUsageEvent, const char *pchExtraInfo) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUser021::TrackAppUsageEvent>(m_original);
            if constexpr (requires { p->TrackAppUsageEvent(o, gameID, eAppUsageEvent, pchExtraInfo); })
                return p->TrackAppUsageEvent(o, gameID, eAppUsageEvent, pchExtraInfo);
            else
                return o(gameID, eAppUsageEvent, pchExtraInfo);
        }(m_proxy);
    }

    bool GetUserDataFolder(char *pchBuffer, int cubBuffer) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUser021::GetUserDataFolder>(m_original);
            if constexpr (requires { p->GetUserDataFolder(o, pchBuffer, cubBuffer); })
                return p->GetUserDataFolder(o, pchBuffer, cubBuffer);
            else
                return o(pchBuffer, cubBuffer);
        }(m_proxy);
    }

    void StartVoiceRecording() override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUser021::StartVoiceRecording>(m_original);
            if constexpr (requires { p->StartVoiceRecording(o); })
                return p->StartVoiceRecording(o);
            else
                return o();
        }(m_proxy);
    }

    void StopVoiceRecording() override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUser021::StopVoiceRecording>(m_original);
            if constexpr (requires { p->StopVoiceRecording(o); })
                return p->StopVoiceRecording(o);
            else
                return o();
        }(m_proxy);
    }

    EVoiceResult GetAvailableVoice(uint32 *pcbCompressed, uint32 *pcbUncompressed_Deprecated, uint32 nUncompressedVoiceDesiredSampleRate_Deprecated) override
    {
        return [&](auto p) -> EVoiceResult
        {
            auto o = MakeOrig<&ISteamUser021::GetAvailableVoice>(m_original);
            if constexpr (requires { p->GetAvailableVoice(o, pcbCompressed, pcbUncompressed_Deprecated, nUncompressedVoiceDesiredSampleRate_Deprecated); })
                return p->GetAvailableVoice(o, pcbCompressed, pcbUncompressed_Deprecated, nUncompressedVoiceDesiredSampleRate_Deprecated);
            else
                return o(pcbCompressed, pcbUncompressed_Deprecated, nUncompressedVoiceDesiredSampleRate_Deprecated);
        }(m_proxy);
    }

    EVoiceResult GetVoice(bool bWantCompressed, void *pDestBuffer, uint32 cbDestBufferSize, uint32 *nBytesWritten, bool bWantUncompressed_Deprecated, void *pUncompressedDestBuffer_Deprecated, uint32 cbUncompressedDestBufferSize_Deprecated, uint32 *nUncompressBytesWritten_Deprecated, uint32 nUncompressedVoiceDesiredSampleRate_Deprecated) override
    {
        return [&](auto p) -> EVoiceResult
        {
            auto o = MakeOrig<&ISteamUser021::GetVoice>(m_original);
            if constexpr (requires { p->GetVoice(o, bWantCompressed, pDestBuffer, cbDestBufferSize, nBytesWritten, bWantUncompressed_Deprecated, pUncompressedDestBuffer_Deprecated, cbUncompressedDestBufferSize_Deprecated, nUncompressBytesWritten_Deprecated, nUncompressedVoiceDesiredSampleRate_Deprecated); })
                return p->GetVoice(o, bWantCompressed, pDestBuffer, cbDestBufferSize, nBytesWritten, bWantUncompressed_Deprecated, pUncompressedDestBuffer_Deprecated, cbUncompressedDestBufferSize_Deprecated, nUncompressBytesWritten_Deprecated, nUncompressedVoiceDesiredSampleRate_Deprecated);
            else
                return o(bWantCompressed, pDestBuffer, cbDestBufferSize, nBytesWritten, bWantUncompressed_Deprecated, pUncompressedDestBuffer_Deprecated, cbUncompressedDestBufferSize_Deprecated, nUncompressBytesWritten_Deprecated, nUncompressedVoiceDesiredSampleRate_Deprecated);
        }(m_proxy);
    }

    EVoiceResult DecompressVoice(const void *pCompressed, uint32 cbCompressed, void *pDestBuffer, uint32 cbDestBufferSize, uint32 *nBytesWritten, uint32 nDesiredSampleRate) override
    {
        return [&](auto p) -> EVoiceResult
        {
            auto o = MakeOrig<&ISteamUser021::DecompressVoice>(m_original);
            if constexpr (requires { p->DecompressVoice(o, pCompressed, cbCompressed, pDestBuffer, cbDestBufferSize, nBytesWritten, nDesiredSampleRate); })
                return p->DecompressVoice(o, pCompressed, cbCompressed, pDestBuffer, cbDestBufferSize, nBytesWritten, nDesiredSampleRate);
            else
                return o(pCompressed, cbCompressed, pDestBuffer, cbDestBufferSize, nBytesWritten, nDesiredSampleRate);
        }(m_proxy);
    }

    uint32 GetVoiceOptimalSampleRate() override
    {
        return [&](auto p) -> uint32
        {
            auto o = MakeOrig<&ISteamUser021::GetVoiceOptimalSampleRate>(m_original);
            if constexpr (requires { p->GetVoiceOptimalSampleRate(o); })
                return p->GetVoiceOptimalSampleRate(o);
            else
                return o();
        }(m_proxy);
    }

    HAuthTicket GetAuthSessionTicket(void *pTicket, int cbMaxTicket, uint32 *pcbTicket) override
    {
        return [&](auto p) -> HAuthTicket
        {
            auto o = MakeOrig<&ISteamUser021::GetAuthSessionTicket>(m_original);
            if constexpr (requires { p->GetAuthSessionTicket(o, pTicket, cbMaxTicket, pcbTicket); })
                return p->GetAuthSessionTicket(o, pTicket, cbMaxTicket, pcbTicket);
            else
                return o(pTicket, cbMaxTicket, pcbTicket);
        }(m_proxy);
    }

    EBeginAuthSessionResult BeginAuthSession(const void *pAuthTicket, int cbAuthTicket, CSteamID steamID) override
    {
        return [&](auto p) -> EBeginAuthSessionResult
        {
            auto o = MakeOrig<&ISteamUser021::BeginAuthSession>(m_original);
            if constexpr (requires { p->BeginAuthSession(o, pAuthTicket, cbAuthTicket, steamID); })
                return p->BeginAuthSession(o, pAuthTicket, cbAuthTicket, steamID);
            else
                return o(pAuthTicket, cbAuthTicket, steamID);
        }(m_proxy);
    }

    void EndAuthSession(CSteamID steamID) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUser021::EndAuthSession>(m_original);
            if constexpr (requires { p->EndAuthSession(o, steamID); })
                return p->EndAuthSession(o, steamID);
            else
                return o(steamID);
        }(m_proxy);
    }

    void CancelAuthTicket(HAuthTicket hAuthTicket) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUser021::CancelAuthTicket>(m_original);
            if constexpr (requires { p->CancelAuthTicket(o, hAuthTicket); })
                return p->CancelAuthTicket(o, hAuthTicket);
            else
                return o(hAuthTicket);
        }(m_proxy);
    }

    EUserHasLicenseForAppResult UserHasLicenseForApp(CSteamID steamID, AppId_t appID) override
    {
        return [&](auto p) -> EUserHasLicenseForAppResult
        {
            auto o = MakeOrig<&ISteamUser021::UserHasLicenseForApp>(m_original);
            if constexpr (requires { p->UserHasLicenseForApp(o, steamID, appID); })
                return p->UserHasLicenseForApp(o, steamID, appID);
            else
                return o(steamID, appID);
        }(m_proxy);
    }

    bool BIsBehindNAT() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUser021::BIsBehindNAT>(m_original);
            if constexpr (requires { p->BIsBehindNAT(o); })
                return p->BIsBehindNAT(o);
            else
                return o();
        }(m_proxy);
    }

    void AdvertiseGame(CSteamID steamIDGameServer, uint32 unIPServer, uint16 usPortServer) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUser021::AdvertiseGame>(m_original);
            if constexpr (requires { p->AdvertiseGame(o, steamIDGameServer, unIPServer, usPortServer); })
                return p->AdvertiseGame(o, steamIDGameServer, unIPServer, usPortServer);
            else
                return o(steamIDGameServer, unIPServer, usPortServer);
        }(m_proxy);
    }

    SteamAPICall_t RequestEncryptedAppTicket(void *pDataToInclude, int cbDataToInclude) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamUser021::RequestEncryptedAppTicket>(m_original);
            if constexpr (requires { p->RequestEncryptedAppTicket(o, pDataToInclude, cbDataToInclude); })
                return p->RequestEncryptedAppTicket(o, pDataToInclude, cbDataToInclude);
            else
                return o(pDataToInclude, cbDataToInclude);
        }(m_proxy);
    }

    bool GetEncryptedAppTicket(void *pTicket, int cbMaxTicket, uint32 *pcbTicket) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUser021::GetEncryptedAppTicket>(m_original);
            if constexpr (requires { p->GetEncryptedAppTicket(o, pTicket, cbMaxTicket, pcbTicket); })
                return p->GetEncryptedAppTicket(o, pTicket, cbMaxTicket, pcbTicket);
            else
                return o(pTicket, cbMaxTicket, pcbTicket);
        }(m_proxy);
    }

    int GetGameBadgeLevel(int nSeries, bool bFoil) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamUser021::GetGameBadgeLevel>(m_original);
            if constexpr (requires { p->GetGameBadgeLevel(o, nSeries, bFoil); })
                return p->GetGameBadgeLevel(o, nSeries, bFoil);
            else
                return o(nSeries, bFoil);
        }(m_proxy);
    }

    int GetPlayerSteamLevel() override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamUser021::GetPlayerSteamLevel>(m_original);
            if constexpr (requires { p->GetPlayerSteamLevel(o); })
                return p->GetPlayerSteamLevel(o);
            else
                return o();
        }(m_proxy);
    }

    SteamAPICall_t RequestStoreAuthURL(const char *pchRedirectURL) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamUser021::RequestStoreAuthURL>(m_original);
            if constexpr (requires { p->RequestStoreAuthURL(o, pchRedirectURL); })
                return p->RequestStoreAuthURL(o, pchRedirectURL);
            else
                return o(pchRedirectURL);
        }(m_proxy);
    }

    bool BIsPhoneVerified() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUser021::BIsPhoneVerified>(m_original);
            if constexpr (requires { p->BIsPhoneVerified(o); })
                return p->BIsPhoneVerified(o);
            else
                return o();
        }(m_proxy);
    }

    bool BIsTwoFactorEnabled() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUser021::BIsTwoFactorEnabled>(m_original);
            if constexpr (requires { p->BIsTwoFactorEnabled(o); })
                return p->BIsTwoFactorEnabled(o);
            else
                return o();
        }(m_proxy);
    }

    bool BIsPhoneIdentifying() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUser021::BIsPhoneIdentifying>(m_original);
            if constexpr (requires { p->BIsPhoneIdentifying(o); })
                return p->BIsPhoneIdentifying(o);
            else
                return o();
        }(m_proxy);
    }

    bool BIsPhoneRequiringVerification() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUser021::BIsPhoneRequiringVerification>(m_original);
            if constexpr (requires { p->BIsPhoneRequiringVerification(o); })
                return p->BIsPhoneRequiringVerification(o);
            else
                return o();
        }(m_proxy);
    }

    SteamAPICall_t GetMarketEligibility() override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamUser021::GetMarketEligibility>(m_original);
            if constexpr (requires { p->GetMarketEligibility(o); })
                return p->GetMarketEligibility(o);
            else
                return o();
        }(m_proxy);
    }

    SteamAPICall_t GetDurationControl() override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamUser021::GetDurationControl>(m_original);
            if constexpr (requires { p->GetDurationControl(o); })
                return p->GetDurationControl(o);
            else
                return o();
        }(m_proxy);
    }

    bool BSetDurationControlOnlineState(EDurationControlOnlineState eNewState) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUser021::BSetDurationControlOnlineState>(m_original);
            if constexpr (requires { p->BSetDurationControlOnlineState(o, eNewState); })
                return p->BSetDurationControlOnlineState(o, eNewState);
            else
                return o(eNewState);
        }(m_proxy);
    }
};

#endif // STEAMUSERPROXY021_H
