// Automatically generated by scripts/steamproxygen.py, do not modify!!!
#ifndef STEAMUTILSPROXY002_H
#define STEAMUTILSPROXY002_H

#include "steamproxy.h"
#include <steam_old/isteamutils002.h>

class SteamUtilsProxy002 final : public ISteamUtils002
{
    ISteamUtils002 *m_original;
    SteamUtilsProxy *m_proxy;

public:
    SteamUtilsProxy002(ISteamUtils002 *original, SteamUtilsProxy *proxy)
        : m_original{ original }
        , m_proxy{ proxy }
    {
    }

    uint32 GetSecondsSinceAppActive() override
    {
        return [&](auto p) -> uint32
        {
            auto o = MakeOrig<&ISteamUtils002::GetSecondsSinceAppActive>(m_original);
            if constexpr (requires { p->GetSecondsSinceAppActive(o); })
                return p->GetSecondsSinceAppActive(o);
            else
                return o();
        }(m_proxy);
    }

    uint32 GetSecondsSinceComputerActive() override
    {
        return [&](auto p) -> uint32
        {
            auto o = MakeOrig<&ISteamUtils002::GetSecondsSinceComputerActive>(m_original);
            if constexpr (requires { p->GetSecondsSinceComputerActive(o); })
                return p->GetSecondsSinceComputerActive(o);
            else
                return o();
        }(m_proxy);
    }

    EUniverse GetConnectedUniverse() override
    {
        return [&](auto p) -> EUniverse
        {
            auto o = MakeOrig<&ISteamUtils002::GetConnectedUniverse>(m_original);
            if constexpr (requires { p->GetConnectedUniverse(o); })
                return p->GetConnectedUniverse(o);
            else
                return o();
        }(m_proxy);
    }

    uint32 GetServerRealTime() override
    {
        return [&](auto p) -> uint32
        {
            auto o = MakeOrig<&ISteamUtils002::GetServerRealTime>(m_original);
            if constexpr (requires { p->GetServerRealTime(o); })
                return p->GetServerRealTime(o);
            else
                return o();
        }(m_proxy);
    }

    const char *GetIPCountry() override
    {
        return [&](auto p) -> const char *
        {
            auto o = MakeOrig<&ISteamUtils002::GetIPCountry>(m_original);
            if constexpr (requires { p->GetIPCountry(o); })
                return p->GetIPCountry(o);
            else
                return o();
        }(m_proxy);
    }

    bool GetImageSize(int iImage, uint32 *pnWidth, uint32 *pnHeight) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils002::GetImageSize>(m_original);
            if constexpr (requires { p->GetImageSize(o, iImage, pnWidth, pnHeight); })
                return p->GetImageSize(o, iImage, pnWidth, pnHeight);
            else
                return o(iImage, pnWidth, pnHeight);
        }(m_proxy);
    }

    bool GetImageRGBA(int iImage, uint8 *pubDest, int nDestBufferSize) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils002::GetImageRGBA>(m_original);
            if constexpr (requires { p->GetImageRGBA(o, iImage, pubDest, nDestBufferSize); })
                return p->GetImageRGBA(o, iImage, pubDest, nDestBufferSize);
            else
                return o(iImage, pubDest, nDestBufferSize);
        }(m_proxy);
    }

    bool GetCSERIPPort(uint32 *unIP, uint16 *usPort) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils002::GetCSERIPPort>(m_original);
            if constexpr (requires { p->GetCSERIPPort(o, unIP, usPort); })
                return p->GetCSERIPPort(o, unIP, usPort);
            else
                return o(unIP, usPort);
        }(m_proxy);
    }

    uint8 GetCurrentBatteryPower() override
    {
        return [&](auto p) -> uint8
        {
            auto o = MakeOrig<&ISteamUtils002::GetCurrentBatteryPower>(m_original);
            if constexpr (requires { p->GetCurrentBatteryPower(o); })
                return p->GetCurrentBatteryPower(o);
            else
                return o();
        }(m_proxy);
    }

    uint32 GetAppID() override
    {
        return [&](auto p) -> uint32
        {
            auto o = MakeOrig<&ISteamUtils002::GetAppID>(m_original);
            if constexpr (requires { p->GetAppID(o); })
                return p->GetAppID(o);
            else
                return o();
        }(m_proxy);
    }

    void SetOverlayNotificationPosition(ENotificationPosition eNotificationPosition) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUtils002::SetOverlayNotificationPosition>(m_original);
            if constexpr (requires { p->SetOverlayNotificationPosition(o, eNotificationPosition); })
                return p->SetOverlayNotificationPosition(o, eNotificationPosition);
            else
                return o(eNotificationPosition);
        }(m_proxy);
    }

    bool IsAPICallCompleted(SteamAPICall_t hSteamAPICall, bool *pbFailed) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils002::IsAPICallCompleted>(m_original);
            if constexpr (requires { p->IsAPICallCompleted(o, hSteamAPICall, pbFailed); })
                return p->IsAPICallCompleted(o, hSteamAPICall, pbFailed);
            else
                return o(hSteamAPICall, pbFailed);
        }(m_proxy);
    }

    ESteamAPICallFailure GetAPICallFailureReason(SteamAPICall_t hSteamAPICall) override
    {
        return [&](auto p) -> ESteamAPICallFailure
        {
            auto o = MakeOrig<&ISteamUtils002::GetAPICallFailureReason>(m_original);
            if constexpr (requires { p->GetAPICallFailureReason(o, hSteamAPICall); })
                return p->GetAPICallFailureReason(o, hSteamAPICall);
            else
                return o(hSteamAPICall);
        }(m_proxy);
    }

    bool GetAPICallResult(SteamAPICall_t hSteamAPICall, void *pCallback, int cubCallback, int iCallbackExpected, bool *pbFailed) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUtils002::GetAPICallResult>(m_original);
            if constexpr (requires { p->GetAPICallResult(o, hSteamAPICall, pCallback, cubCallback, iCallbackExpected, pbFailed); })
                return p->GetAPICallResult(o, hSteamAPICall, pCallback, cubCallback, iCallbackExpected, pbFailed);
            else
                return o(hSteamAPICall, pCallback, cubCallback, iCallbackExpected, pbFailed);
        }(m_proxy);
    }
};

#endif // STEAMUTILSPROXY002_H
