// Automatically generated by scripts/steamproxygen.py, do not modify!!!
#ifndef STEAMGAMESERVERPROXY010_H
#define STEAMGAMESERVERPROXY010_H

#include "steamproxy.h"
#include <steam_old/isteamgameserver010.h>

class SteamGameServerProxy010 final : public ISteamGameServer010
{
    ISteamGameServer010 *m_original;
    SteamGameServerProxy *m_proxy;

public:
    SteamGameServerProxy010(ISteamGameServer010 *original, SteamGameServerProxy *proxy)
        : m_original{ original }
        , m_proxy{ proxy }
    {
    }

    void LogOn() override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer010::LogOn>(m_original);
            if constexpr (requires { p->LogOn(o); })
                return p->LogOn(o);
            else
                return o();
        }(m_proxy);
    }

    void LogOff() override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer010::LogOff>(m_original);
            if constexpr (requires { p->LogOff(o); })
                return p->LogOff(o);
            else
                return o();
        }(m_proxy);
    }

    bool BLoggedOn() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamGameServer010::BLoggedOn>(m_original);
            if constexpr (requires { p->BLoggedOn(o); })
                return p->BLoggedOn(o);
            else
                return o();
        }(m_proxy);
    }

    bool BSecure() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamGameServer010::BSecure>(m_original);
            if constexpr (requires { p->BSecure(o); })
                return p->BSecure(o);
            else
                return o();
        }(m_proxy);
    }

    CSteamID GetSteamID() override
    {
        return [&](auto p) -> CSteamID
        {
            auto o = MakeOrig<&ISteamGameServer010::GetSteamID>(m_original);
            if constexpr (requires { p->GetSteamID(o); })
                return p->GetSteamID(o);
            else
                return o();
        }(m_proxy);
    }

    bool SendUserConnectAndAuthenticate(uint32 unIPClient, const void *pvAuthBlob, uint32 cubAuthBlobSize, CSteamID *pSteamIDUser) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamGameServer010::SendUserConnectAndAuthenticate>(m_original);
            if constexpr (requires { p->SendUserConnectAndAuthenticate(o, unIPClient, pvAuthBlob, cubAuthBlobSize, pSteamIDUser); })
                return p->SendUserConnectAndAuthenticate(o, unIPClient, pvAuthBlob, cubAuthBlobSize, pSteamIDUser);
            else
                return o(unIPClient, pvAuthBlob, cubAuthBlobSize, pSteamIDUser);
        }(m_proxy);
    }

    CSteamID CreateUnauthenticatedUserConnection() override
    {
        return [&](auto p) -> CSteamID
        {
            auto o = MakeOrig<&ISteamGameServer010::CreateUnauthenticatedUserConnection>(m_original);
            if constexpr (requires { p->CreateUnauthenticatedUserConnection(o); })
                return p->CreateUnauthenticatedUserConnection(o);
            else
                return o();
        }(m_proxy);
    }

    void SendUserDisconnect(CSteamID steamIDUser) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer010::SendUserDisconnect>(m_original);
            if constexpr (requires { p->SendUserDisconnect(o, steamIDUser); })
                return p->SendUserDisconnect(o, steamIDUser);
            else
                return o(steamIDUser);
        }(m_proxy);
    }

    bool BUpdateUserData(CSteamID steamIDUser, const char *pchPlayerName, uint32 uScore) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamGameServer010::BUpdateUserData>(m_original);
            if constexpr (requires { p->BUpdateUserData(o, steamIDUser, pchPlayerName, uScore); })
                return p->BUpdateUserData(o, steamIDUser, pchPlayerName, uScore);
            else
                return o(steamIDUser, pchPlayerName, uScore);
        }(m_proxy);
    }

    bool BSetServerType(uint32 unServerFlags, uint32 unGameIP, uint16 unGamePort, uint16 unSpectatorPort, uint16 usQueryPort, const char *pchGameDir, const char *pchVersion, bool bLANMode) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamGameServer010::BSetServerType>(m_original);
            if constexpr (requires { p->BSetServerType(o, unServerFlags, unGameIP, unGamePort, unSpectatorPort, usQueryPort, pchGameDir, pchVersion, bLANMode); })
                return p->BSetServerType(o, unServerFlags, unGameIP, unGamePort, unSpectatorPort, usQueryPort, pchGameDir, pchVersion, bLANMode);
            else
                return o(unServerFlags, unGameIP, unGamePort, unSpectatorPort, usQueryPort, pchGameDir, pchVersion, bLANMode);
        }(m_proxy);
    }

    void UpdateServerStatus(int cPlayers, int cPlayersMax, int cBotPlayers, const char *pchServerName, const char *pSpectatorServerName, const char *pchMapName) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer010::UpdateServerStatus>(m_original);
            if constexpr (requires { p->UpdateServerStatus(o, cPlayers, cPlayersMax, cBotPlayers, pchServerName, pSpectatorServerName, pchMapName); })
                return p->UpdateServerStatus(o, cPlayers, cPlayersMax, cBotPlayers, pchServerName, pSpectatorServerName, pchMapName);
            else
                return o(cPlayers, cPlayersMax, cBotPlayers, pchServerName, pSpectatorServerName, pchMapName);
        }(m_proxy);
    }

    void UpdateSpectatorPort(uint16 unSpectatorPort) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer010::UpdateSpectatorPort>(m_original);
            if constexpr (requires { p->UpdateSpectatorPort(o, unSpectatorPort); })
                return p->UpdateSpectatorPort(o, unSpectatorPort);
            else
                return o(unSpectatorPort);
        }(m_proxy);
    }

    void SetGameTags(const char *pchGameTags) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer010::SetGameTags>(m_original);
            if constexpr (requires { p->SetGameTags(o, pchGameTags); })
                return p->SetGameTags(o, pchGameTags);
            else
                return o(pchGameTags);
        }(m_proxy);
    }

    void GetGameplayStats() override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer010::GetGameplayStats>(m_original);
            if constexpr (requires { p->GetGameplayStats(o); })
                return p->GetGameplayStats(o);
            else
                return o();
        }(m_proxy);
    }

    SteamAPICall_t GetServerReputation() override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamGameServer010::GetServerReputation>(m_original);
            if constexpr (requires { p->GetServerReputation(o); })
                return p->GetServerReputation(o);
            else
                return o();
        }(m_proxy);
    }

    bool RequestUserGroupStatus(CSteamID steamIDUser, CSteamID steamIDGroup) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamGameServer010::RequestUserGroupStatus>(m_original);
            if constexpr (requires { p->RequestUserGroupStatus(o, steamIDUser, steamIDGroup); })
                return p->RequestUserGroupStatus(o, steamIDUser, steamIDGroup);
            else
                return o(steamIDUser, steamIDGroup);
        }(m_proxy);
    }

    uint32 GetPublicIP() override
    {
        return [&](auto p) -> uint32
        {
            auto o = MakeOrig<&ISteamGameServer010::GetPublicIP>(m_original);
            if constexpr (requires { p->GetPublicIP(o); })
                return p->GetPublicIP(o);
            else
                return o();
        }(m_proxy);
    }

    void SetGameData(const char *pchGameData) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer010::SetGameData>(m_original);
            if constexpr (requires { p->SetGameData(o, pchGameData); })
                return p->SetGameData(o, pchGameData);
            else
                return o(pchGameData);
        }(m_proxy);
    }

    EUserHasLicenseForAppResult UserHasLicenseForApp(CSteamID steamID, AppId_t appID) override
    {
        return [&](auto p) -> EUserHasLicenseForAppResult
        {
            auto o = MakeOrig<&ISteamGameServer010::UserHasLicenseForApp>(m_original);
            if constexpr (requires { p->UserHasLicenseForApp(o, steamID, appID); })
                return p->UserHasLicenseForApp(o, steamID, appID);
            else
                return o(steamID, appID);
        }(m_proxy);
    }

    HAuthTicket GetAuthSessionTicket(void *pTicket, int cbMaxTicket, uint32 *pcbTicket) override
    {
        return [&](auto p) -> HAuthTicket
        {
            auto o = MakeOrig<&ISteamGameServer010::GetAuthSessionTicket>(m_original);
            if constexpr (requires { p->GetAuthSessionTicket(o, pTicket, cbMaxTicket, pcbTicket); })
                return p->GetAuthSessionTicket(o, pTicket, cbMaxTicket, pcbTicket);
            else
                return o(pTicket, cbMaxTicket, pcbTicket);
        }(m_proxy);
    }

    EBeginAuthSessionResult BeginAuthSession(const void *pAuthTicket, int cbAuthTicket, CSteamID steamID) override
    {
        return [&](auto p) -> EBeginAuthSessionResult
        {
            auto o = MakeOrig<&ISteamGameServer010::BeginAuthSession>(m_original);
            if constexpr (requires { p->BeginAuthSession(o, pAuthTicket, cbAuthTicket, steamID); })
                return p->BeginAuthSession(o, pAuthTicket, cbAuthTicket, steamID);
            else
                return o(pAuthTicket, cbAuthTicket, steamID);
        }(m_proxy);
    }

    void EndAuthSession(CSteamID steamID) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer010::EndAuthSession>(m_original);
            if constexpr (requires { p->EndAuthSession(o, steamID); })
                return p->EndAuthSession(o, steamID);
            else
                return o(steamID);
        }(m_proxy);
    }

    void CancelAuthTicket(HAuthTicket hAuthTicket) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamGameServer010::CancelAuthTicket>(m_original);
            if constexpr (requires { p->CancelAuthTicket(o, hAuthTicket); })
                return p->CancelAuthTicket(o, hAuthTicket);
            else
                return o(hAuthTicket);
        }(m_proxy);
    }
};

#endif // STEAMGAMESERVERPROXY010_H
