// Automatically generated by scripts/steamproxygen.py, do not modify!!!
#ifndef STEAMCLIENTPROXY016_H
#define STEAMCLIENTPROXY016_H

#include "steamproxy.h"
#include <steam_old/isteamclient016.h>

class SteamClientProxy016 final : public ISteamClient016
{
    ISteamClient016 *m_original;
    SteamClientProxy *m_proxy;

public:
    SteamClientProxy016(ISteamClient016 *original, SteamClientProxy *proxy)
        : m_original{ original }
        , m_proxy{ proxy }
    {
    }

    HSteamPipe CreateSteamPipe() override
    {
        return [&](auto p) -> HSteamPipe
        {
            auto o = MakeOrig<&ISteamClient016::CreateSteamPipe>(m_original);
            if constexpr (requires { p->CreateSteamPipe(o); })
                return p->CreateSteamPipe(o);
            else
                return o();
        }(m_proxy);
    }

    bool BReleaseSteamPipe(HSteamPipe hSteamPipe) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamClient016::BReleaseSteamPipe>(m_original);
            if constexpr (requires { p->BReleaseSteamPipe(o, hSteamPipe); })
                return p->BReleaseSteamPipe(o, hSteamPipe);
            else
                return o(hSteamPipe);
        }(m_proxy);
    }

    HSteamUser ConnectToGlobalUser(HSteamPipe hSteamPipe) override
    {
        return [&](auto p) -> HSteamUser
        {
            auto o = MakeOrig<&ISteamClient016::ConnectToGlobalUser>(m_original);
            if constexpr (requires { p->ConnectToGlobalUser(o, hSteamPipe); })
                return p->ConnectToGlobalUser(o, hSteamPipe);
            else
                return o(hSteamPipe);
        }(m_proxy);
    }

    HSteamUser CreateLocalUser(HSteamPipe *phSteamPipe, EAccountType eAccountType) override
    {
        return [&](auto p) -> HSteamUser
        {
            auto o = MakeOrig<&ISteamClient016::CreateLocalUser>(m_original);
            if constexpr (requires { p->CreateLocalUser(o, phSteamPipe, eAccountType); })
                return p->CreateLocalUser(o, phSteamPipe, eAccountType);
            else
                return o(phSteamPipe, eAccountType);
        }(m_proxy);
    }

    void ReleaseUser(HSteamPipe hSteamPipe, HSteamUser hUser) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamClient016::ReleaseUser>(m_original);
            if constexpr (requires { p->ReleaseUser(o, hSteamPipe, hUser); })
                return p->ReleaseUser(o, hSteamPipe, hUser);
            else
                return o(hSteamPipe, hUser);
        }(m_proxy);
    }

    ISteamUser *GetISteamUser(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamUser *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamUser>(m_original);
            if constexpr (requires { p->GetISteamUser(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamUser(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamGameServer *GetISteamGameServer(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamGameServer *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamGameServer>(m_original);
            if constexpr (requires { p->GetISteamGameServer(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamGameServer(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    void SetLocalIPBinding(uint32 unIP, uint16 usPort) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamClient016::SetLocalIPBinding>(m_original);
            if constexpr (requires { p->SetLocalIPBinding(o, unIP, usPort); })
                return p->SetLocalIPBinding(o, unIP, usPort);
            else
                return o(unIP, usPort);
        }(m_proxy);
    }

    ISteamFriends *GetISteamFriends(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamFriends *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamFriends>(m_original);
            if constexpr (requires { p->GetISteamFriends(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamFriends(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamUtils *GetISteamUtils(HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamUtils *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamUtils>(m_original);
            if constexpr (requires { p->GetISteamUtils(o, hSteamPipe, pchVersion); })
                return p->GetISteamUtils(o, hSteamPipe, pchVersion);
            else
                return o(hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamMatchmaking *GetISteamMatchmaking(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamMatchmaking *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamMatchmaking>(m_original);
            if constexpr (requires { p->GetISteamMatchmaking(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamMatchmaking(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamMatchmakingServers *GetISteamMatchmakingServers(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamMatchmakingServers *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamMatchmakingServers>(m_original);
            if constexpr (requires { p->GetISteamMatchmakingServers(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamMatchmakingServers(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    void *GetISteamGenericInterface(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> void *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamGenericInterface>(m_original);
            if constexpr (requires { p->GetISteamGenericInterface(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamGenericInterface(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamUserStats *GetISteamUserStats(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamUserStats *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamUserStats>(m_original);
            if constexpr (requires { p->GetISteamUserStats(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamUserStats(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamGameServerStats *GetISteamGameServerStats(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamGameServerStats *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamGameServerStats>(m_original);
            if constexpr (requires { p->GetISteamGameServerStats(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamGameServerStats(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamApps *GetISteamApps(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamApps *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamApps>(m_original);
            if constexpr (requires { p->GetISteamApps(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamApps(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamNetworking *GetISteamNetworking(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamNetworking *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamNetworking>(m_original);
            if constexpr (requires { p->GetISteamNetworking(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamNetworking(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamRemoteStorage *GetISteamRemoteStorage(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamRemoteStorage *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamRemoteStorage>(m_original);
            if constexpr (requires { p->GetISteamRemoteStorage(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamRemoteStorage(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamScreenshots *GetISteamScreenshots(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamScreenshots *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamScreenshots>(m_original);
            if constexpr (requires { p->GetISteamScreenshots(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamScreenshots(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    void RunFrame() override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamClient016::RunFrame>(m_original);
            if constexpr (requires { p->RunFrame(o); })
                return p->RunFrame(o);
            else
                return o();
        }(m_proxy);
    }

    uint32 GetIPCCallCount() override
    {
        return [&](auto p) -> uint32
        {
            auto o = MakeOrig<&ISteamClient016::GetIPCCallCount>(m_original);
            if constexpr (requires { p->GetIPCCallCount(o); })
                return p->GetIPCCallCount(o);
            else
                return o();
        }(m_proxy);
    }

    void SetWarningMessageHook(SteamAPIWarningMessageHook_t pFunction) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamClient016::SetWarningMessageHook>(m_original);
            if constexpr (requires { p->SetWarningMessageHook(o, pFunction); })
                return p->SetWarningMessageHook(o, pFunction);
            else
                return o(pFunction);
        }(m_proxy);
    }

    bool BShutdownIfAllPipesClosed() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamClient016::BShutdownIfAllPipesClosed>(m_original);
            if constexpr (requires { p->BShutdownIfAllPipesClosed(o); })
                return p->BShutdownIfAllPipesClosed(o);
            else
                return o();
        }(m_proxy);
    }

    ISteamHTTP *GetISteamHTTP(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamHTTP *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamHTTP>(m_original);
            if constexpr (requires { p->GetISteamHTTP(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamHTTP(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamUnifiedMessages *GetISteamUnifiedMessages(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamUnifiedMessages *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamUnifiedMessages>(m_original);
            if constexpr (requires { p->GetISteamUnifiedMessages(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamUnifiedMessages(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamController *GetISteamController(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamController *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamController>(m_original);
            if constexpr (requires { p->GetISteamController(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamController(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamUGC *GetISteamUGC(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamUGC *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamUGC>(m_original);
            if constexpr (requires { p->GetISteamUGC(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamUGC(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamAppList *GetISteamAppList(HSteamUser hSteamUser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamAppList *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamAppList>(m_original);
            if constexpr (requires { p->GetISteamAppList(o, hSteamUser, hSteamPipe, pchVersion); })
                return p->GetISteamAppList(o, hSteamUser, hSteamPipe, pchVersion);
            else
                return o(hSteamUser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamMusic *GetISteamMusic(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamMusic *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamMusic>(m_original);
            if constexpr (requires { p->GetISteamMusic(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamMusic(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamMusicRemote *GetISteamMusicRemote(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamMusicRemote *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamMusicRemote>(m_original);
            if constexpr (requires { p->GetISteamMusicRemote(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamMusicRemote(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    ISteamHTMLSurface *GetISteamHTMLSurface(HSteamUser hSteamuser, HSteamPipe hSteamPipe, const char *pchVersion) override
    {
        return [&](auto p) -> ISteamHTMLSurface *
        {
            auto o = MakeOrig<&ISteamClient016::GetISteamHTMLSurface>(m_original);
            if constexpr (requires { p->GetISteamHTMLSurface(o, hSteamuser, hSteamPipe, pchVersion); })
                return p->GetISteamHTMLSurface(o, hSteamuser, hSteamPipe, pchVersion);
            else
                return o(hSteamuser, hSteamPipe, pchVersion);
        }(m_proxy);
    }

    void Set_SteamAPI_CPostAPIResultInProcess(SteamAPI_PostAPIResultInProcess_t func) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamClient016::Set_SteamAPI_CPostAPIResultInProcess>(m_original);
            if constexpr (requires { p->Set_SteamAPI_CPostAPIResultInProcess(o, func); })
                return p->Set_SteamAPI_CPostAPIResultInProcess(o, func);
            else
                return o(func);
        }(m_proxy);
    }

    void Remove_SteamAPI_CPostAPIResultInProcess(SteamAPI_PostAPIResultInProcess_t func) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamClient016::Remove_SteamAPI_CPostAPIResultInProcess>(m_original);
            if constexpr (requires { p->Remove_SteamAPI_CPostAPIResultInProcess(o, func); })
                return p->Remove_SteamAPI_CPostAPIResultInProcess(o, func);
            else
                return o(func);
        }(m_proxy);
    }

    void Set_SteamAPI_CCheckCallbackRegisteredInProcess(SteamAPI_CheckCallbackRegistered_t func) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamClient016::Set_SteamAPI_CCheckCallbackRegisteredInProcess>(m_original);
            if constexpr (requires { p->Set_SteamAPI_CCheckCallbackRegisteredInProcess(o, func); })
                return p->Set_SteamAPI_CCheckCallbackRegisteredInProcess(o, func);
            else
                return o(func);
        }(m_proxy);
    }
};

#endif // STEAMCLIENTPROXY016_H
