// Automatically generated by scripts/steamproxygen.py, do not modify!!!
#ifndef STEAMUSERPROXY015_H
#define STEAMUSERPROXY015_H

#include "steamproxy.h"
#include <steam_old/isteamuser015.h>

class SteamUserProxy015 final : public ISteamUser015
{
    ISteamUser015 *m_original;
    SteamUserProxy *m_proxy;

public:
    SteamUserProxy015(ISteamUser015 *original, SteamUserProxy *proxy)
        : m_original{ original }
        , m_proxy{ proxy }
    {
    }

    HSteamUser GetHSteamUser() override
    {
        return [&](auto p) -> HSteamUser
        {
            auto o = MakeOrig<&ISteamUser015::GetHSteamUser>(m_original);
            if constexpr (requires { p->GetHSteamUser(o); })
                return p->GetHSteamUser(o);
            else
                return o();
        }(m_proxy);
    }

    bool BLoggedOn() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUser015::BLoggedOn>(m_original);
            if constexpr (requires { p->BLoggedOn(o); })
                return p->BLoggedOn(o);
            else
                return o();
        }(m_proxy);
    }

    CSteamID GetSteamID() override
    {
        return [&](auto p) -> CSteamID
        {
            auto o = MakeOrig<&ISteamUser015::GetSteamID>(m_original);
            if constexpr (requires { p->GetSteamID(o); })
                return p->GetSteamID(o);
            else
                return o();
        }(m_proxy);
    }

    int InitiateGameConnection(void *pAuthBlob, int cbMaxAuthBlob, CSteamID steamIDGameServer, uint32 unIPServer, uint16 usPortServer, bool bSecure) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamUser015::InitiateGameConnection>(m_original);
            if constexpr (requires { p->InitiateGameConnection(o, pAuthBlob, cbMaxAuthBlob, steamIDGameServer, unIPServer, usPortServer, bSecure); })
                return p->InitiateGameConnection(o, pAuthBlob, cbMaxAuthBlob, steamIDGameServer, unIPServer, usPortServer, bSecure);
            else
                return o(pAuthBlob, cbMaxAuthBlob, steamIDGameServer, unIPServer, usPortServer, bSecure);
        }(m_proxy);
    }

    void TerminateGameConnection(uint32 unIPServer, uint16 usPortServer) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUser015::TerminateGameConnection>(m_original);
            if constexpr (requires { p->TerminateGameConnection(o, unIPServer, usPortServer); })
                return p->TerminateGameConnection(o, unIPServer, usPortServer);
            else
                return o(unIPServer, usPortServer);
        }(m_proxy);
    }

    void TrackAppUsageEvent(CGameID gameID, int eAppUsageEvent, const char *pchExtraInfo) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUser015::TrackAppUsageEvent>(m_original);
            if constexpr (requires { p->TrackAppUsageEvent(o, gameID, eAppUsageEvent, pchExtraInfo); })
                return p->TrackAppUsageEvent(o, gameID, eAppUsageEvent, pchExtraInfo);
            else
                return o(gameID, eAppUsageEvent, pchExtraInfo);
        }(m_proxy);
    }

    bool GetUserDataFolder(char *pchBuffer, int cubBuffer) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUser015::GetUserDataFolder>(m_original);
            if constexpr (requires { p->GetUserDataFolder(o, pchBuffer, cubBuffer); })
                return p->GetUserDataFolder(o, pchBuffer, cubBuffer);
            else
                return o(pchBuffer, cubBuffer);
        }(m_proxy);
    }

    void StartVoiceRecording() override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUser015::StartVoiceRecording>(m_original);
            if constexpr (requires { p->StartVoiceRecording(o); })
                return p->StartVoiceRecording(o);
            else
                return o();
        }(m_proxy);
    }

    void StopVoiceRecording() override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUser015::StopVoiceRecording>(m_original);
            if constexpr (requires { p->StopVoiceRecording(o); })
                return p->StopVoiceRecording(o);
            else
                return o();
        }(m_proxy);
    }

    EVoiceResult GetAvailableVoice(uint32 *pcbCompressed, uint32 *pcbUncompressed) override
    {
        return [&](auto p) -> EVoiceResult
        {
            auto o = MakeOrig<&ISteamUser015::GetAvailableVoice>(m_original);
            if constexpr (requires { p->GetAvailableVoice(o, pcbCompressed, pcbUncompressed); })
                return p->GetAvailableVoice(o, pcbCompressed, pcbUncompressed);
            else
                return o(pcbCompressed, pcbUncompressed);
        }(m_proxy);
    }

    EVoiceResult GetVoice(bool bWantCompressed, void *pDestBuffer, uint32 cbDestBufferSize, uint32 *nBytesWritten, bool bWantUncompressed, void *pUncompressedDestBuffer, uint32 cbUncompressedDestBufferSize, uint32 *nUncompressBytesWritten) override
    {
        return [&](auto p) -> EVoiceResult
        {
            auto o = MakeOrig<&ISteamUser015::GetVoice>(m_original);
            if constexpr (requires { p->GetVoice(o, bWantCompressed, pDestBuffer, cbDestBufferSize, nBytesWritten, bWantUncompressed, pUncompressedDestBuffer, cbUncompressedDestBufferSize, nUncompressBytesWritten); })
                return p->GetVoice(o, bWantCompressed, pDestBuffer, cbDestBufferSize, nBytesWritten, bWantUncompressed, pUncompressedDestBuffer, cbUncompressedDestBufferSize, nUncompressBytesWritten);
            else
                return o(bWantCompressed, pDestBuffer, cbDestBufferSize, nBytesWritten, bWantUncompressed, pUncompressedDestBuffer, cbUncompressedDestBufferSize, nUncompressBytesWritten);
        }(m_proxy);
    }

    EVoiceResult DecompressVoice(const void *pCompressed, uint32 cbCompressed, void *pDestBuffer, uint32 cbDestBufferSize, uint32 *nBytesWritten, uint32 nDesiredSampleRate) override
    {
        return [&](auto p) -> EVoiceResult
        {
            auto o = MakeOrig<&ISteamUser015::DecompressVoice>(m_original);
            if constexpr (requires { p->DecompressVoice(o, pCompressed, cbCompressed, pDestBuffer, cbDestBufferSize, nBytesWritten, nDesiredSampleRate); })
                return p->DecompressVoice(o, pCompressed, cbCompressed, pDestBuffer, cbDestBufferSize, nBytesWritten, nDesiredSampleRate);
            else
                return o(pCompressed, cbCompressed, pDestBuffer, cbDestBufferSize, nBytesWritten, nDesiredSampleRate);
        }(m_proxy);
    }

    uint32 GetVoiceOptimalSampleRate() override
    {
        return [&](auto p) -> uint32
        {
            auto o = MakeOrig<&ISteamUser015::GetVoiceOptimalSampleRate>(m_original);
            if constexpr (requires { p->GetVoiceOptimalSampleRate(o); })
                return p->GetVoiceOptimalSampleRate(o);
            else
                return o();
        }(m_proxy);
    }

    HAuthTicket GetAuthSessionTicket(void *pTicket, int cbMaxTicket, uint32 *pcbTicket) override
    {
        return [&](auto p) -> HAuthTicket
        {
            auto o = MakeOrig<&ISteamUser015::GetAuthSessionTicket>(m_original);
            if constexpr (requires { p->GetAuthSessionTicket(o, pTicket, cbMaxTicket, pcbTicket); })
                return p->GetAuthSessionTicket(o, pTicket, cbMaxTicket, pcbTicket);
            else
                return o(pTicket, cbMaxTicket, pcbTicket);
        }(m_proxy);
    }

    EBeginAuthSessionResult BeginAuthSession(const void *pAuthTicket, int cbAuthTicket, CSteamID steamID) override
    {
        return [&](auto p) -> EBeginAuthSessionResult
        {
            auto o = MakeOrig<&ISteamUser015::BeginAuthSession>(m_original);
            if constexpr (requires { p->BeginAuthSession(o, pAuthTicket, cbAuthTicket, steamID); })
                return p->BeginAuthSession(o, pAuthTicket, cbAuthTicket, steamID);
            else
                return o(pAuthTicket, cbAuthTicket, steamID);
        }(m_proxy);
    }

    void EndAuthSession(CSteamID steamID) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUser015::EndAuthSession>(m_original);
            if constexpr (requires { p->EndAuthSession(o, steamID); })
                return p->EndAuthSession(o, steamID);
            else
                return o(steamID);
        }(m_proxy);
    }

    void CancelAuthTicket(HAuthTicket hAuthTicket) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUser015::CancelAuthTicket>(m_original);
            if constexpr (requires { p->CancelAuthTicket(o, hAuthTicket); })
                return p->CancelAuthTicket(o, hAuthTicket);
            else
                return o(hAuthTicket);
        }(m_proxy);
    }

    EUserHasLicenseForAppResult UserHasLicenseForApp(CSteamID steamID, AppId_t appID) override
    {
        return [&](auto p) -> EUserHasLicenseForAppResult
        {
            auto o = MakeOrig<&ISteamUser015::UserHasLicenseForApp>(m_original);
            if constexpr (requires { p->UserHasLicenseForApp(o, steamID, appID); })
                return p->UserHasLicenseForApp(o, steamID, appID);
            else
                return o(steamID, appID);
        }(m_proxy);
    }

    bool BIsBehindNAT() override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUser015::BIsBehindNAT>(m_original);
            if constexpr (requires { p->BIsBehindNAT(o); })
                return p->BIsBehindNAT(o);
            else
                return o();
        }(m_proxy);
    }

    void AdvertiseGame(CSteamID steamIDGameServer, uint32 unIPServer, uint16 usPortServer) override
    {
        return [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamUser015::AdvertiseGame>(m_original);
            if constexpr (requires { p->AdvertiseGame(o, steamIDGameServer, unIPServer, usPortServer); })
                return p->AdvertiseGame(o, steamIDGameServer, unIPServer, usPortServer);
            else
                return o(steamIDGameServer, unIPServer, usPortServer);
        }(m_proxy);
    }

    SteamAPICall_t RequestEncryptedAppTicket(void *pDataToInclude, int cbDataToInclude) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamUser015::RequestEncryptedAppTicket>(m_original);
            if constexpr (requires { p->RequestEncryptedAppTicket(o, pDataToInclude, cbDataToInclude); })
                return p->RequestEncryptedAppTicket(o, pDataToInclude, cbDataToInclude);
            else
                return o(pDataToInclude, cbDataToInclude);
        }(m_proxy);
    }

    bool GetEncryptedAppTicket(void *pTicket, int cbMaxTicket, uint32 *pcbTicket) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamUser015::GetEncryptedAppTicket>(m_original);
            if constexpr (requires { p->GetEncryptedAppTicket(o, pTicket, cbMaxTicket, pcbTicket); })
                return p->GetEncryptedAppTicket(o, pTicket, cbMaxTicket, pcbTicket);
            else
                return o(pTicket, cbMaxTicket, pcbTicket);
        }(m_proxy);
    }
};

#endif // STEAMUSERPROXY015_H
